In [1]:
import polars as pl
import os
from pathlib import Path

In [2]:
DATA_DIR=Path("../../Sepsis-data/data/raw_data_phase2_v2")
os.listdir(DATA_DIR)

['Encounters - Mar 2025 - Feb 2026 - 3.31.26.csv',
 'Lab Results - 3.9.26.csv',
 'Flowsheet - 3.9.26.csv',
 'Procedure Orders - 3.9.26.csv',
 'Encounters with Scores and Flags - Mar 2025 - Feb 2026 - 3.31.26.csv',
 'Diagnoses - 3.9.26.csv',
 'Flowsheet SBP - 3.9.26.csv',
 'Encounter Table with Baseline Values - Mar 2025 - Feb 2026 - 3.25.26.csv',
 'Med Admin - 3.9.26.csv',
 'Scores and Flags - Mar 2025 - Feb 2026 - 3.31.26.csv',
 'Flowsheet Events Feb 2025 - Mar 2026 - 3.31.26.csv',
 'Encounter Table with Baseline Values - Mar 2025 - Feb 2026.csv',
 'Flowsheet - 3.24.26.csv']

In [3]:
df_kelsea = pl.read_csv(DATA_DIR/Path("Scores and Flags - Mar 2025 - Feb 2026 - 3.31.26.csv"), infer_schema=False, null_values=['Null', "NULL", 'null'])

In [4]:
df_kelsea

shape: (1_929_174, 60)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Most_Rece ┆ Most_Rece ┆ … ┆ Organ_Dys ┆ Severe_Se ┆ Septic_Sh ┆ FirstAdm │
│ EpicCsn   ┆ eTime     ┆ nt_Temp_i ┆ nt_Pulse_ ┆   ┆ function  ┆ psis      ┆ ock       ┆ issionOr │
│ ---       ┆ ---       ┆ n_8       ┆ in_8      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ derInsta │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ nt       │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 699476058 ┆ 2024-04-3 ┆ 97.50     ┆ 94.00     ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 2024-04- │
│           ┆ 0 06:15:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30 21:55 │
│           ┆ 0.0000000 ┆           ┆           ┆   ┆           ┆           ┆           ┆ :00.000  │
│ 699476058 ┆ 2024-04-3 ┆ 97.50     ┆ 94.00     ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 2024-04- │
│           ┆ 0 07:05:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30 21:55 │
│           ┆ 0.0000000 ┆           ┆           ┆   ┆           ┆           ┆           ┆ :00.000  │
│ 699476058 ┆ 2024-04-3 ┆ 97.50     ┆ 94.00     ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 2024-04- │
│           ┆ 0 09:14:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30 21:55 │
│           ┆ 0.0000000 ┆           ┆           ┆   ┆           ┆           ┆           ┆ :00.000  │
│ 699476058 ┆ 2024-04-3 ┆ 97.50     ┆ 94.00     ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 2024-04- │
│           ┆ 0 10:26:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30 21:55 │
│           ┆ 0.0000000 ┆           ┆           ┆   ┆           ┆           ┆           ┆ :00.000  │
│ 699476058 ┆ 2024-04-3 ┆ 97.50     ┆ 94.00     ┆ … ┆ 1         ┆ 1         ┆ 0         ┆ 2024-04- │
│           ┆ 0 11:24:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30 21:55 │
│           ┆ 0.0000000 ┆           ┆           ┆   ┆           ┆           ┆           ┆ :00.000  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 747311714 ┆ 2026-02-2 ┆ 98.80     ┆ 64.00     ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 2026-02- │
│           ┆ 7 09:33:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25 23:01 │
│           ┆ 0.0000000 ┆           ┆           ┆   ┆           ┆           ┆           ┆ :00.000  │
│ 747311714 ┆ 2026-02-2 ┆ 98.80     ┆ 67.00     ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 2026-02- │
│           ┆ 7 11:14:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25 23:01 │
│           ┆ 0.0000000 ┆           ┆           ┆   ┆           ┆           ┆           ┆ :00.000  │
│ 747311714 ┆ 2026-02-2 ┆ 98.80     ┆ 66.00     ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 2026-02- │
│           ┆ 7 11:15:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25 23:01 │
│           ┆ 0.0000000 ┆           ┆           ┆   ┆           ┆           ┆           ┆ :00.000  │
│ 747311714 ┆ 2026-02-2 ┆ 98.80     ┆ 62.00     ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 2026-02- │
│           ┆ 7 11:17:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25 23:01 │
│           ┆ 0.0000000 ┆           ┆           ┆   ┆           ┆           ┆           ┆ :00.000  │
│ 747311714 ┆ 2026-02-2 ┆ 98.80     ┆ 60.00     ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 2026-02- │
│           ┆ 7 11:18:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25 23:01 │
│           ┆ 0.0000000 ┆           ┆           ┆   ┆           ┆           ┆           ┆ :00.000  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
datetime_cols = [
    'FirstAdmissionOrderInstant',
	'Event_DateTime',
]

df_kelsea = df_kelsea.with_columns(
	pl.col(datetime_cols).str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S.%f")
)

/tmp/ipykernel_3788501/1377335737.py:7: ChronoFormatWarning: Detected the pattern `.%f` in the chrono format string. This pattern should not be used to parse values after a decimal point. Use `%.f` instead. See the full specification: https://docs.rs/chrono/latest/chrono/format/strftime
  pl.col(datetime_cols).str.strptime(pl.Datetime, format="%Y-%m-%d %H:%M:%S.%f")

In [13]:
STR_COLS = ['Last_Vent_Change', 'O2_Delivery_High_Flow']

In [17]:
df_kscores = df_kelsea.with_columns(
    pl.col(set(df_kelsea.columns) - set(datetime_cols) - set(STR_COLS) -{'EncounterEpicCsn'}).cast(pl.Float64),
    pl.col("EncounterEpicCsn").cast(pl.Int64)
)

# =====================

In [3]:
DATA_DIR=Path("../../Sepsis-data/data/output/raw_data_phase2_v2")
os.listdir(DATA_DIR)

['df_sirs.parquet',
 'df_infect.parquet',
 'df_agg_vent.parquet',
 'df_agg.parquet',
 'df_all.parquet',
 'df_septicshock.parquet',
 'df_organdysfunction.parquet']

In [4]:
df_infect = pl.read_parquet(DATA_DIR/"df_infect.parquet")
df_sirs = pl.read_parquet(DATA_DIR/"df_sirs.parquet")
df_agg_vent = pl.read_parquet(DATA_DIR/"df_agg_vent.parquet")
df_organdysfunction = pl.read_parquet(DATA_DIR/"df_organdysfunction.parquet")
df_septicshock = pl.read_parquet(DATA_DIR/"df_septicshock.parquet")

In [5]:
df_infect.shape, df_infect.unique().shape

((4032, 19), (4032, 19))

In [25]:
df_agg_vent.shape, df_organdysfunction.shape, df_septicshock.shape

((4481895, 22), (4481895, 41), (4481895, 36))

In [74]:
set(df_organdysfunction.columns)-set(df_septicshock.columns)

{'aptt_criteria_flag',
 'cardiovascular_failure_flag',
 'coagulation_failure_flag',
 'hepatic_failure_flag',
 'inr_criteria_flag',
 'neurological_failure_flag',
 'organ_dysfunction_total',
 'platelets100_criteria_flag',
 'platelets50_criteria_flag',
 'pulmonary_failure_flag',
 'renal_failure_flag'}

In [76]:
df_agg_vent = df_agg_vent.sort(by=['EncounterEpicCsn', 'Event_DateTime'])
df_organdysfunction = df_organdysfunction.sort(by=['EncounterEpicCsn', 'Event_DateTime'])
df_septicshock = df_septicshock.sort(by=['EncounterEpicCsn', 'Event_DateTime'])

df_agg_vent.select(
    "EncounterEpicCsn",
	"Event_DateTime",
).equals(
	df_organdysfunction.select(
		"EncounterEpicCsn",
		"Event_DateTime",
	)
), df_organdysfunction.select(
    "EncounterEpicCsn",
	"Event_DateTime",
).equals(
	df_septicshock.select(
		"EncounterEpicCsn",
		"Event_DateTime",
	)
)

(True, True)

In [77]:
df_mo = df_agg_vent
cols = set(df_mo.columns)
df_mo = pl.concat([df_mo, df_organdysfunction.select(set(df_organdysfunction.columns)-set(df_mo.columns))], how='horizontal')
df_mo = pl.concat([df_mo, df_septicshock.select(set(df_septicshock.columns)-set(df_mo.columns))], how='horizontal')

df_mo

shape: (4_481_895, 47)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ last_temp ┆ last_puls ┆ … ┆ vasopress ┆ map65_fla ┆ lactate4_ ┆ sbp90_fl │
│ EpicCsn   ┆ eTime     ┆ _8h       ┆ e_8h      ┆   ┆ or_flag   ┆ g         ┆ flag      ┆ ag       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ i64       ┆ datetime[ ┆ f64       ┆ f64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 699476058 ┆ 2024-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0        │
│           ┆ 6 03:09:3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 7.020     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 699476058 ┆ 2024-04-3 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0        │
│           ┆ 0 03:39:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 3.660     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 699476058 ┆ 2024-04-3 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0        │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:15:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 699476058 ┆ 2024-04-3 ┆ 97.5      ┆ 94.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0        │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:25:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 699476058 ┆ 2024-04-3 ┆ 97.5      ┆ 94.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ 0        │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 07:05:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 747311714 ┆ 2026-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 3 02:39:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 8.620     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 747311714 ┆ 2026-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5 02:40:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.267     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 747311714 ┆ 2026-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5 02:40:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.267     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 747311714 ┆ 2026-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 7 02:31:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 5.340     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 747311714 ┆ 2026-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 7 02:31:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 5.340     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [80]:
df_mo.filter(
    pl.col("septic_shock_flag") > 0
).group_by(
	"EncounterEpicCsn"
).agg(
    pl.col("Event_DateTime").min().alias("first_septic_shock_time")
)

shape: (730, 2)
┌──────────────────┬─────────────────────────┐
│ EncounterEpicCsn ┆ first_septic_shock_time │
│ ---              ┆ ---                     │
│ i64              ┆ datetime[μs]            │
╞══════════════════╪═════════════════════════╡
│ 699476058        ┆ 2024-05-03 02:58:02.690 │
│ 709516764        ┆ 2025-03-15 15:18:00     │
│ 714445951        ┆ 2024-11-03 13:55:00     │
│ 714534044        ┆ 2024-10-27 07:11:00     │
│ 717006646        ┆ 2024-12-20 21:58:00     │
│ …                ┆ …                       │
│ 746624566        ┆ 2026-02-17 17:08:00     │
│ 746672537        ┆ 2026-02-19 06:09:00     │
│ 746859570        ┆ 2026-02-20 04:36:00     │
│ 746919560        ┆ 2026-02-20 01:19:00     │
│ 747311714        ┆ 2026-02-26 03:25:00     │
└──────────────────┴─────────────────────────┘

In [ ]:
df_kscores =df_kscores.sort(by=['EncounterEpicCsn', 'Event_DateTime'])

In [29]:
df_kscores

shape: (1_929_174, 60)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Most_Rece ┆ Most_Rece ┆ … ┆ Organ_Dys ┆ Severe_Se ┆ Septic_Sh ┆ FirstAdm │
│ EpicCsn   ┆ eTime     ┆ nt_Temp_i ┆ nt_Pulse_ ┆   ┆ function  ┆ psis      ┆ ock       ┆ issionOr │
│ ---       ┆ ---       ┆ n_8       ┆ in_8      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ derInsta │
│ i64       ┆ datetime[ ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ nt       │
│           ┆ μs]       ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 699476058 ┆ 2024-04-3 ┆ 97.5      ┆ 94.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 2024-04- │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30       │
│           ┆ 06:15:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 21:55:00 │
│ 699476058 ┆ 2024-04-3 ┆ 97.5      ┆ 94.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 2024-04- │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30       │
│           ┆ 07:05:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 21:55:00 │
│ 699476058 ┆ 2024-04-3 ┆ 97.5      ┆ 94.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 2024-04- │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30       │
│           ┆ 09:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 21:55:00 │
│ 699476058 ┆ 2024-04-3 ┆ 97.5      ┆ 94.0      ┆ … ┆ 1.0       ┆ 1.0       ┆ 0.0       ┆ 2024-04- │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30       │
│           ┆ 10:26:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 21:55:00 │
│ 699476058 ┆ 2024-04-3 ┆ 97.5      ┆ 94.0      ┆ … ┆ 1.0       ┆ 1.0       ┆ 0.0       ┆ 2024-04- │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 30       │
│           ┆ 11:24:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 21:55:00 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 747311714 ┆ 2026-02-2 ┆ 98.8      ┆ 64.0      ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 2026-02- │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25       │
│           ┆ 09:33:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 23:01:00 │
│ 747311714 ┆ 2026-02-2 ┆ 98.8      ┆ 67.0      ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 2026-02- │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25       │
│           ┆ 11:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 23:01:00 │
│ 747311714 ┆ 2026-02-2 ┆ 98.8      ┆ 66.0      ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 2026-02- │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25       │
│           ┆ 11:15:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 23:01:00 │
│ 747311714 ┆ 2026-02-2 ┆ 98.8      ┆ 62.0      ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 2026-02- │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25       │
│           ┆ 11:17:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 23:01:00 │
│ 747311714 ┆ 2026-02-2 ┆ 98.8      ┆ 60.0      ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 2026-02- │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ 25       │
│           ┆ 11:18:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 23:01:00 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
df_agg_vent.sort(by=['EncounterEpicCsn', 'Event_DateTime'])

shape: (4_481_895, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ last_temp ┆ last_puls ┆ … ┆ last_nore ┆ last_epin ┆ vent_stat ┆ vent_sta │
│ EpicCsn   ┆ eTime     ┆ _8h       ┆ e_8h      ┆   ┆ pinephrin ┆ ephrine_2 ┆ us_time   ┆ tus_flag │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e_24h     ┆ 4h        ┆ ---       ┆ ---      │
│ i64       ┆ datetime[ ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ datetime[ ┆ str      │
│           ┆ μs]       ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 699476058 ┆ 2024-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 6 03:09:3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 7.020     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 699476058 ┆ 2024-04-3 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 0 03:39:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 3.660     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 699476058 ┆ 2024-04-3 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:15:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 699476058 ┆ 2024-04-3 ┆ 97.5      ┆ 94.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:25:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 699476058 ┆ 2024-04-3 ┆ 97.5      ┆ 94.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 07:05:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 747311714 ┆ 2026-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆ 3 02:39:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆ 8.620     ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ 747311714 ┆ 2026-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆ 5 02:40:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆ 0.267     ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ 747311714 ┆ 2026-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5 02:40:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 0.267     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 747311714 ┆ 2026-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆ 7 02:31:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆ 5.340     ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ 747311714 ┆ 2026-03-0 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 7 02:31:4 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 5.340     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [32]:
df_all = df_kscores.join(
    df_agg_vent,
	on=['EncounterEpicCsn', 'Event_DateTime'],
	how='outer'
)

/tmp/ipykernel_3788501/82484523.py:1: DeprecationWarning: use of `how='outer'` should be replaced with `how='full'`.
(Deprecated in version 0.20.29)
  df_all = df_kscores.join(

In [35]:
df_all.sort(by=['EncounterEpicCsn', 'Event_DateTime'])

shape: (4_482_937, 82)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Most_Rece ┆ Most_Rece ┆ … ┆ last_nore ┆ last_epin ┆ vent_stat ┆ vent_sta │
│ EpicCsn   ┆ eTime     ┆ nt_Temp_i ┆ nt_Pulse_ ┆   ┆ pinephrin ┆ ephrine_2 ┆ us_time   ┆ tus_flag │
│ ---       ┆ ---       ┆ n_8       ┆ in_8      ┆   ┆ e_24h     ┆ 4h        ┆ ---       ┆ ---      │
│ i64       ┆ datetime[ ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ datetime[ ┆ str      │
│           ┆ μs]       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2025-03-0 ┆ Vent on  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 2         ┆ Document │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 07:50:00  ┆ ation    │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 747311714 ┆ 2026-02-2 ┆ 98.8      ┆ 66.0      ┆ … ┆ 0.25      ┆ 0.07      ┆ null      ┆ null     │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:15:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 747311714 ┆ 2026-02-2 ┆ 98.8      ┆ 62.0      ┆ … ┆ 0.25      ┆ 0.07      ┆ null      ┆ Vent off │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆ 11:17:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ 747311714 ┆ 2026-02-2 ┆ 98.8      ┆ 62.0      ┆ … ┆ 0.25      ┆ 0.07      ┆ null      ┆ null     │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:17:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 747311714 ┆ 2026-02-2 ┆ 98.8      ┆ 60.0      ┆ … ┆ 0.25      ┆ 0.07      ┆ null      ┆ null     │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:18:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 747311714 ┆ 2026-02-2 ┆ 98.8      ┆ 60.0      ┆ … ┆ 0.25      ┆ 0.07      ┆ null      ┆ Vent off │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆ 11:18:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [38]:
[c for c in df_all.columns if 'temp' in c.lower() and ('Most' in c or 'last' in c)]

['Most_Recent_Temp_in_8', 'last_temp_8h']

In [36]:
df_all.filter(
    pl.col("EncounterEpicCsn").is_not_null()&pl.col("EncounterEpicCsn_right").is_not_null()
)

shape: (3_388_417, 82)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Most_Rece ┆ Most_Rece ┆ … ┆ last_nore ┆ last_epin ┆ vent_stat ┆ vent_sta │
│ EpicCsn   ┆ eTime     ┆ nt_Temp_i ┆ nt_Pulse_ ┆   ┆ pinephrin ┆ ephrine_2 ┆ us_time   ┆ tus_flag │
│ ---       ┆ ---       ┆ n_8       ┆ in_8      ┆   ┆ e_24h     ┆ 4h        ┆ ---       ┆ ---      │
│ i64       ┆ datetime[ ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ datetime[ ┆ str      │
│           ┆ μs]       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 714534044 ┆ 2024-12-1 ┆ 98.3      ┆ 130.0     ┆ … ┆ null      ┆ null      ┆ 2024-11-0 ┆ O2       │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ Delivery │
│           ┆ 13:04:00  ┆           ┆           ┆   ┆           ┆           ┆ 19:38:00  ┆ High-Flo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ w        │
│ 714534044 ┆ 2024-12-1 ┆ 98.3      ┆ 130.0     ┆ … ┆ null      ┆ null      ┆ 2024-10-2 ┆ Vent on  │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ Document │
│           ┆ 13:04:00  ┆           ┆           ┆   ┆           ┆           ┆ 04:01:00  ┆ ation    │
│ 730748586 ┆ 2025-07-1 ┆ 97.5      ┆ 77.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 08:56:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 730748586 ┆ 2025-07-1 ┆ 97.5      ┆ 77.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆ 08:56:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ 726699663 ┆ 2025-05-1 ┆ 97.9      ┆ 86.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆ 23:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 741989382 ┆ 2026-02-0 ┆ 98.1      ┆ 92.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:25:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 741989382 ┆ 2026-02-0 ┆ 98.1      ┆ 92.0      ┆ … ┆ null      ┆ null      ┆ 2025-12-1 ┆ Vent off │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ Document │
│           ┆ 11:25:00  ┆           ┆           ┆   ┆           ┆           ┆ 11:15:00  ┆ ation    │
│ 742397959 ┆ 2025-12-1 ┆ 98.1      ┆ 97.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:21:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 742397959 ┆ 2025-12-1 ┆ 98.1      ┆ 97.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆ 20:21:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ 739122655 ┆ 2025-10-2 ┆ 100.2     ┆ 113.0     ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆ 12:04:49  ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [39]:
df_all.filter(
    pl.col("EncounterEpicCsn").is_not_null()&pl.col("EncounterEpicCsn_right").is_not_null()
).select(
    [c for c in df_all.columns if 'temp' in c.lower() and ('Most' in c or 'last' in c)]
)

shape: (3_388_417, 2)
┌───────────────────────┬──────────────┐
│ Most_Recent_Temp_in_8 ┆ last_temp_8h │
│ ---                   ┆ ---          │
│ f64                   ┆ f64          │
╞═══════════════════════╪══════════════╡
│ 98.3                  ┆ 98.3         │
│ 98.3                  ┆ 98.3         │
│ 97.5                  ┆ 97.5         │
│ 97.5                  ┆ 97.5         │
│ 97.9                  ┆ 99.5         │
│ …                     ┆ …            │
│ 98.1                  ┆ 98.1         │
│ 98.1                  ┆ 98.1         │
│ 98.1                  ┆ 97.7         │
│ 98.1                  ┆ 97.7         │
│ 100.2                 ┆ null         │
└───────────────────────┴──────────────┘

In [ ]:

temp_cols = [c for c in df_all.columns if 'pulse' in c.lower() and ('Most' in c or 'last' in c)]
df_all.filter(
    pl.col("EncounterEpicCsn").is_not_null()&pl.col("EncounterEpicCsn_right").is_not_null()
).with_columns(
    (pl.col(temp_cols[0])==pl.col(temp_cols[1])).mean().alias('match_rate'),
    pl.corr(temp_cols[0], temp_cols[1]).alias('correlation'),
	(pl.col(temp_cols[0]) - pl.col(temp_cols[1])).abs().mean().alias('difference')

).select('match_rate', 'correlation', 'difference')

shape: (3_388_417, 3)
┌────────────┬─────────────┬────────────┐
│ match_rate ┆ correlation ┆ difference │
│ ---        ┆ ---         ┆ ---        │
│ f64        ┆ f64         ┆ f64        │
╞════════════╪═════════════╪════════════╡
│ 0.311476   ┆ 0.928688    ┆ 3.755012   │
│ 0.311476   ┆ 0.928688    ┆ 3.755012   │
│ 0.311476   ┆ 0.928688    ┆ 3.755012   │
│ 0.311476   ┆ 0.928688    ┆ 3.755012   │
│ 0.311476   ┆ 0.928688    ┆ 3.755012   │
│ …          ┆ …           ┆ …          │
│ 0.311476   ┆ 0.928688    ┆ 3.755012   │
│ 0.311476   ┆ 0.928688    ┆ 3.755012   │
│ 0.311476   ┆ 0.928688    ┆ 3.755012   │
│ 0.311476   ┆ 0.928688    ┆ 3.755012   │
│ 0.311476   ┆ 0.928688    ┆ 3.755012   │
└────────────┴─────────────┴────────────┘

In [46]:
df_all.filter(
	(pl.col("EncounterEpicCsn").is_not_null()&pl.col("EncounterEpicCsn_right").is_not_null())&
	(pl.col(temp_cols[0])!=pl.col(temp_cols[1]))
).select("EncounterEpicCsn", "Event_DateTime").sort(by=['EncounterEpicCsn', 'Event_DateTime'])

shape: (549_728, 2)
┌──────────────────┬─────────────────────┐
│ EncounterEpicCsn ┆ Event_DateTime      │
│ ---              ┆ ---                 │
│ i64              ┆ datetime[μs]        │
╞══════════════════╪═════════════════════╡
│ 699476058        ┆ 2024-04-30 22:40:00 │
│ 699476058        ┆ 2024-05-01 00:00:00 │
│ 699476058        ┆ 2024-05-01 04:00:00 │
│ 699476058        ┆ 2024-05-01 04:35:00 │
│ 699476058        ┆ 2024-05-01 05:00:00 │
│ …                ┆ …                   │
│ 747311714        ┆ 2026-02-27 05:00:00 │
│ 747311714        ┆ 2026-02-27 07:00:00 │
│ 747311714        ┆ 2026-02-27 07:00:00 │
│ 747311714        ┆ 2026-02-27 09:00:00 │
│ 747311714        ┆ 2026-02-27 09:00:00 │
└──────────────────┴─────────────────────┘

In [50]:
df_kscores.columns

['EncounterEpicCsn',
 'Event_DateTime',
 'Most_Recent_Temp_in_8',
 'Most_Recent_Pulse_in_8',
 'Most_Recent_Respirations_in_8',
 'Most_Recent_WBC_in_12',
 'Max_Vasopressin_Dose',
 'Max_Phenylephrine_Dose',
 'Max_Norepinephrine_Dose',
 'Max_Epinephrine_Dose',
 'Most_Recent_Creatinine_in_12',
 'Most_Recent_eGFR_in_12',
 'Most_Recent_Bilirubin_in_12',
 'Most_Recent_Lactate_in_6',
 'Most_Recent_Platelet_Count_in_24',
 'Most_Recent_INR_in_12',
 'Most_Recent_APTT_in_24',
 'Last_Vent_Change',
 'O2_Delivery_High_Flow',
 'Most_Recent_MAP_in_8',
 'Most_Recent_GCS_in_8',
 'Most_Recent_SBP_in_8',
 'Vent_Status',
 'High_Flow_O2',
 'SIRS',
 'Temp_High_Flag',
 'Temp_Low_Flag',
 'Temp_Abnormal_Flag',
 'HR_High_Flag',
 'Resp_Rate_High_Flag',
 'WBC_High_Flag',
 'WBC_Low_Flag',
 'WBC_Abnormal_Flag',
 'SBP_90',
 'SBP_Delta_40',
 'MAP',
 'Hypotensive',
 'Pulm_Dysfunction',
 'Creatinine_2',
 'Creatinine_2x',
 'eGFR_5',
 'Urine_5',
 'Renal_Dysfunction',
 'Bilirubin_2',
 'Bilirubin_2x',
 'Hep_Dysfunction',
 'Platelet_100',
 'Platelet_5',
 'INR_15',
 'aPTT_60',
 'Coag_Dysfunction',
 'Lactate_2',
 'GCS_15',
 'Neuro_Dysfunction',
 'Cardio_Dysfunction',
 'Vasopressor',
 'Organ_Dysfunction',
 'Severe_Sepsis',
 'Septic_Shock',
 'FirstAdmissionOrderInstant']

In [ ]:
vitals = [
    'temp',
    'pulse',
    'respirations',
    'wbc',
    'map',
    'sbp'
]

labs = [
    'egfr',
	'creatinine',
	'lactate',
	'Platelet',
	'bilirubin',
	'inr',
    # 'aptt',
    'urine',
]

shape: (4_482_937, 82)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Most_Rece ┆ Most_Rece ┆ … ┆ last_nore ┆ last_epin ┆ vent_stat ┆ vent_sta │
│ EpicCsn   ┆ eTime     ┆ nt_Temp_i ┆ nt_Pulse_ ┆   ┆ pinephrin ┆ ephrine_2 ┆ us_time   ┆ tus_flag │
│ ---       ┆ ---       ┆ n_8       ┆ in_8      ┆   ┆ e_24h     ┆ 4h        ┆ ---       ┆ ---      │
│ i64       ┆ datetime[ ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ datetime[ ┆ str      │
│           ┆ μs]       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 714534044 ┆ 2024-12-1 ┆ 98.3      ┆ 130.0     ┆ … ┆ null      ┆ null      ┆ 2024-11-0 ┆ O2       │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ 8         ┆ Delivery │
│           ┆ 13:04:00  ┆           ┆           ┆   ┆           ┆           ┆ 19:38:00  ┆ High-Flo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ w        │
│ 714534044 ┆ 2024-12-1 ┆ 98.3      ┆ 130.0     ┆ … ┆ null      ┆ null      ┆ 2024-10-2 ┆ Vent on  │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆ 7         ┆ Document │
│           ┆ 13:04:00  ┆           ┆           ┆   ┆           ┆           ┆ 04:01:00  ┆ ation    │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ 730748586 ┆ 2025-07-1 ┆ 97.5      ┆ 77.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 08:56:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 730748586 ┆ 2025-07-1 ┆ 97.5      ┆ 77.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ Vent off │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆ Document │
│           ┆ 08:56:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ ation    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 743312356 ┆ 2025-12-3 ┆ 97.9      ┆ 96.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 05:09:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 743312356 ┆ 2026-01-1 ┆ 98.6      ┆ 106.0     ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 04:44:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 743312356 ┆ 2026-02-0 ┆ 98.6      ┆ 88.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:09:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 746991198 ┆ 2026-02-2 ┆ 97.9      ┆ 114.0     ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 2         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:52:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 744484508 ┆ 2026-02-1 ┆ 97.9      ┆ 75.0      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 04:23:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [56]:
def get_column_pairs(event_name, df_cols):
	return [
		c  for c in df_cols if event_name.lower() in c.lower() and ('Most' in c or 'last' in c)
	]

get_column_pairs(labs[3], df_all.columns)

['Most_Recent_Platelet_Count_in_24', 'last_platelets_24h']

In [67]:
for l in vitals:
	col_pairs = get_column_pairs(l, df_all.columns)
	if len(col_pairs) != 2:
		print(f'{l} does not have 2 matching columns. {col_pairs} found ...')
		continue
	n_rows = df_all.filter(
		pl.col("EncounterEpicCsn").is_not_null()&pl.col("EncounterEpicCsn_right").is_not_null()
	).shape[0]

	print(l)
	print(df_all.filter(
		pl.col("EncounterEpicCsn").is_not_null()&pl.col("EncounterEpicCsn_right").is_not_null()
	).select(
		["EncounterEpicCsn",
		"EncounterEpicCsn_right",
		"Event_DateTime",
		"Event_DateTime_right"]+
		col_pairs
	).with_columns(
		(pl.col(col_pairs[0])==pl.col(col_pairs[1])).mean().alias('match_rate'),
		( (pl.col(col_pairs[0])!=pl.col(col_pairs[1])).sum()/n_rows ).alias('num_mismatch_match'),

		pl.corr(col_pairs[0], col_pairs[1]).alias('correlation'),
		(pl.col(col_pairs[0]) - pl.col(col_pairs[1])).abs().mean().alias('difference')
	).select("match_rate", "num_mismatch_match", "correlation", "difference")[0])
	print("===============================================")

temp
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.832791   ┆ 0.162237           ┆ 0.877787    ┆ 0.105532   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
pulse
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.311476   ┆ 0.680742           ┆ 0.928688    ┆ 3.755012   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
respirations does not have 2 matching columns. ['Most_Recent_Respirations_in_8'] found ...
wbc
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.984916   ┆ 0.009629           ┆ 0.999055    ┆ 0.028247   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
map
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.291583   ┆ 0.236864           ┆ 0.787241    ┆ 4.439028   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
sbp
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.557296   ┆ 0.35853            ┆ 0.612419    ┆ 6.882632   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================

In [66]:
for l in labs:
	col_pairs = get_column_pairs(l, df_all.columns)
	if len(col_pairs) != 2:
		print(f'{l} does not have 2 matching columns. {col_pairs} found ...')
		continue
	n_rows = df_all.filter(
		pl.col("EncounterEpicCsn").is_not_null()&pl.col("EncounterEpicCsn_right").is_not_null()
	).shape[0]

	print(l)
	print(df_all.filter(
		pl.col("EncounterEpicCsn").is_not_null()&pl.col("EncounterEpicCsn_right").is_not_null()
	).select(
		["EncounterEpicCsn",
		"EncounterEpicCsn_right",
		"Event_DateTime",
		"Event_DateTime_right"]+
		col_pairs
	).with_columns(
		(pl.col(col_pairs[0])==pl.col(col_pairs[1])).mean().alias('match_rate'),
		( (pl.col(col_pairs[0])!=pl.col(col_pairs[1])).sum()/n_rows ).alias('num_mismatch_match'),

		pl.corr(col_pairs[0], col_pairs[1]).alias('correlation'),
		(pl.col(col_pairs[0]) - pl.col(col_pairs[1])).abs().mean().alias('difference')
	).select("match_rate", "num_mismatch_match", "correlation", "difference")[0])
	print("===============================================")

egfr
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.97894    ┆ 0.014746           ┆ 0.999609    ┆ 0.102203   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
creatinine
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.976731   ┆ 0.016607           ┆ 0.999508    ┆ 0.003491   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
lactate
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.97509    ┆ 0.004583           ┆ 0.998138    ┆ 0.022309   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
Platelet
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.974034   ┆ 0.023853           ┆ 0.999162    ┆ 0.583245   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
bilirubin
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.996661   ┆ 0.00119            ┆ 0.999958    ┆ 0.001784   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
inr
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ 0.996135   ┆ 0.000663           ┆ 0.997133    ┆ 0.001662   │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
aptt
shape: (1, 4)
┌────────────┬────────────────────┬─────────────┬────────────┐
│ match_rate ┆ num_mismatch_match ┆ correlation ┆ difference │
│ ---        ┆ ---                ┆ ---         ┆ ---        │
│ f64        ┆ f64                ┆ f64         ┆ f64        │
╞════════════╪════════════════════╪═════════════╪════════════╡
│ null       ┆ 0.0                ┆ NaN         ┆ null       │
└────────────┴────────────────────┴─────────────┴────────────┘
===============================================
urine does not have 2 matching columns. [] found ...

In [68]:
df_all.columns

['EncounterEpicCsn',
 'Event_DateTime',
 'Most_Recent_Temp_in_8',
 'Most_Recent_Pulse_in_8',
 'Most_Recent_Respirations_in_8',
 'Most_Recent_WBC_in_12',
 'Max_Vasopressin_Dose',
 'Max_Phenylephrine_Dose',
 'Max_Norepinephrine_Dose',
 'Max_Epinephrine_Dose',
 'Most_Recent_Creatinine_in_12',
 'Most_Recent_eGFR_in_12',
 'Most_Recent_Bilirubin_in_12',
 'Most_Recent_Lactate_in_6',
 'Most_Recent_Platelet_Count_in_24',
 'Most_Recent_INR_in_12',
 'Most_Recent_APTT_in_24',
 'Last_Vent_Change',
 'O2_Delivery_High_Flow',
 'Most_Recent_MAP_in_8',
 'Most_Recent_GCS_in_8',
 'Most_Recent_SBP_in_8',
 'Vent_Status',
 'High_Flow_O2',
 'SIRS',
 'Temp_High_Flag',
 'Temp_Low_Flag',
 'Temp_Abnormal_Flag',
 'HR_High_Flag',
 'Resp_Rate_High_Flag',
 'WBC_High_Flag',
 'WBC_Low_Flag',
 'WBC_Abnormal_Flag',
 'SBP_90',
 'SBP_Delta_40',
 'MAP',
 'Hypotensive',
 'Pulm_Dysfunction',
 'Creatinine_2',
 'Creatinine_2x',
 'eGFR_5',
 'Urine_5',
 'Renal_Dysfunction',
 'Bilirubin_2',
 'Bilirubin_2x',
 'Hep_Dysfunction',
 'Platelet_100',
 'Platelet_5',
 'INR_15',
 'aPTT_60',
 'Coag_Dysfunction',
 'Lactate_2',
 'GCS_15',
 'Neuro_Dysfunction',
 'Cardio_Dysfunction',
 'Vasopressor',
 'Organ_Dysfunction',
 'Severe_Sepsis',
 'Septic_Shock',
 'FirstAdmissionOrderInstant',
 'EncounterEpicCsn_right',
 'Event_DateTime_right',
 'last_temp_8h',
 'last_pulse_8h',
 'last_resp_8h',
 'last_sbp_8h',
 'last_map_8h',
 'last_wbc_12h',
 'last_creatinine_12h',
 'last_egfr_12h',
 'last_bilirubin_12h',
 'last_lactate_6h',
 'last_platelets_24h',
 'last_inr_12h',
 'last_aptt_24h',
 'last_gcs_12h',
 'last_vasopressin_24h',
 'last_phenylephrine_24h',
 'last_norepinephrine_24h',
 'last_epinephrine_24h',
 'vent_status_time',
 'vent_status_flag']