In [1]:
import polars as pl
import numpy as np
import duckdb
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import os
from collections import defaultdict
import datetime as dt
from pathlib import Path
import sys
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.ticker as mticker
sys.path.insert(1, os.path.abspath(".."))
os.chdir(os.path.abspath('..')) # Change the workdir to the parent folder

# ── Visual defaults ───────────────────────────────────────────────
sns.set_theme(style="whitegrid", palette="muted")
SIRS_COLORS = {0: "#4CAF50", 1: "#FFC107", 2: "#FF9800", 3: "#F44336", 4: "#9C27B0"}

In [2]:
from src.configs.dataconfig import input_filenames_v3, input_output_config_3, input_filenames_v2, input_output_config_2
from src.dataloader import DataLoader

In [ ]:
df_all_v2 = DataLoader(input_output_config_2).load_data()
df_all_v3 = DataLoader(input_output_config_3).load_data()

In [ ]:
PROJECT_V3 = 'phase3_v3'
PROJECT_V2 = 'raw_data_phase3_v2_old'

### Load output data

In [ ]:
# v3 
df_sepsis_3_v3 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V3,'df_sepsis3.parquet'
	)
)

df_sepsis_2_v3 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V3,'df_sepsis2.parquet'
	)
)

df_sepsis_1_v3 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V3,'df_sepsis1.parquet'
	)
)

df_sirs_3 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V3,'df_sirs_postagg.parquet'
	)
)

df_organdysf_3 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V3,'df_organdysfunction.parquet'
	)
)

df_o2vent_3 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V3,'df_o2vent.parquet'
	)
)

df_shock_3 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path), PROJECT_V3, 'df_septicshock.parquet'
	)
)

df_infect_long_3 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V3,'df_infect_long.parquet'
	)
)

In [ ]:
# v2 
df_sepsis_3_v2 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V2,'df_sepsis3.parquet'
    )
)
df_sepsis_2_v2 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V2,'df_sepsis2.parquet'
    )
)
df_sepsis_1_v2 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V2,'df_sepsis1.parquet'
    )
)


df_sirs_2 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path), PROJECT_V2,'df_sirs.parquet'
	)
)

df_organdysf_2 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path), PROJECT_V2,'df_organdysfunction.parquet'
	)
)

df_o2vent_2 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V2,'df_agg_vent.parquet'
	)
)

df_shock_2 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path), PROJECT_V2, 'df_septicshock.parquet'
	)
)

df_infect_long_2 = pl.read_parquet(
    os.path.join(
        os.path.dirname(input_output_config_3.output_path),PROJECT_V2,'df_infect_long.parquet'
	)
)

### Concatenate

In [ ]:
cols1 = df_sepsis_1_v3.columns
cols2 = df_sepsis_1_v3.columns
cols3 = df_sepsis_1_v3.columns
idx = cols2.index('earliest_sepsis1_instance')
cols2[idx] = 'earliest_sepsis2_instance'
cols3[idx] = 'earliest_sepsis3_instance'
cols2.remove('sirs_score')
cols3.remove('sirs_score')
cols1.remove('sirs_score')

In [ ]:
df_sepsis_1_v3 = df_sepsis_1_v3.select(
    cols1
).with_columns(
    pl.lit(1).alias('sepsis_score')
).rename({"earliest_sepsis1_instance": "sepsis_instance"})

df_sepsis_2_v3 = df_sepsis_2_v3.select(
    cols2
).with_columns(
    pl.lit(2).alias('sepsis_score')
).rename({"earliest_sepsis2_instance": "sepsis_instance"})

df_sepsis_3_v3 = df_sepsis_3_v3.select(
    cols3
).with_columns(
    pl.lit(3).alias('sepsis_score')
).rename({"earliest_sepsis3_instance": "sepsis_instance"})

df_sepsis_v3 = pl.concat([df_sepsis_1_v3, df_sepsis_2_v3, df_sepsis_3_v3], how='vertical')

In [ ]:
df_sepsis_1_v2 = df_sepsis_1_v2.select(
    cols1
).with_columns(
    pl.lit(1).alias('sepsis_score')
).rename({"earliest_sepsis1_instance": "sepsis_instance"})

df_sepsis_2_v2 = df_sepsis_2_v2.select(
    cols2
).with_columns(
    pl.lit(2).alias('sepsis_score')
).rename({"earliest_sepsis2_instance": "sepsis_instance"})

df_sepsis_3_v2 = df_sepsis_3_v2.select(
    cols3
).with_columns(
    pl.lit(3).alias('sepsis_score')
).rename({"earliest_sepsis3_instance": "sepsis_instance"})

df_sepsis_v2 = pl.concat([df_sepsis_1_v2, df_sepsis_2_v2, df_sepsis_3_v2], how='vertical')

### Conflict between v2 and v3

In [ ]:
# First sepsis onset v3
df_sepsis_v3_firstonset = df_sepsis_v3.join(
    df_sepsis_v3.group_by("EncounterEpicCsn").agg(
    pl.col("sepsis_instance").min().alias('first_sepsis_instant')
    ),
	on='EncounterEpicCsn',
	how='inner'
).filter(
    pl.col("sepsis_instance")==pl.col("first_sepsis_instant")
).group_by(
    "EncounterEpicCsn", "first_sepsis_instant"
).agg(
    pl.col("sepsis_score").max(),
    pl.col("infect_dt").min().alias('min_infect_dt'),
    pl.col("infect_dt").max().alias('max_infect_dt'),
    pl.col("Event_DateTime").min().alias('min_Event_DateTime'),
    pl.col("Event_DateTime").max().alias('max_Event_DateTime'),
).sort(by=["EncounterEpicCsn", 'first_sepsis_instant'])
df_sepsis_v3_firstonset

shape: (13_878, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ EncounterEpi ┆ first_sepsi ┆ sepsis_scor ┆ min_infect_ ┆ max_infect_ ┆ min_Event_D ┆ max_Event_D │
│ cCsn         ┆ s_instant   ┆ e           ┆ dt          ┆ dt          ┆ ateTime     ┆ ateTime     │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ i64          ┆ datetime[μs ┆ i32         ┆ datetime[μs ┆ datetime[μs ┆ datetime[μs ┆ datetime[μs │
│              ┆ ]           ┆             ┆ ]           ┆ ]           ┆ ]           ┆ ]           │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 659308243    ┆ 2022-06-14  ┆ 2           ┆ 2022-06-14  ┆ 2022-06-15  ┆ 2022-06-14  ┆ 2022-06-14  │
│              ┆ 16:40:00    ┆             ┆ 22:10:00    ┆ 23:40:38    ┆ 16:40:00    ┆ 16:40:00    │
│ 660956097    ┆ 2022-06-27  ┆ 2           ┆ 2022-06-28  ┆ 2022-06-28  ┆ 2022-06-27  ┆ 2022-06-27  │
│              ┆ 23:58:00    ┆             ┆ 06:10:00    ┆ 10:39:00    ┆ 23:58:00    ┆ 23:58:00    │
│ 661424247    ┆ 2022-08-28  ┆ 1           ┆ 2022-08-28  ┆ 2022-08-28  ┆ 2022-08-28  ┆ 2022-08-28  │
│              ┆ 04:56:00    ┆             ┆ 05:30:00    ┆ 10:56:00    ┆ 04:56:00    ┆ 04:56:00    │
│ 661471289    ┆ 2022-06-07  ┆ 2           ┆ 2022-06-07  ┆ 2022-06-08  ┆ 2022-06-07  ┆ 2022-06-07  │
│              ┆ 12:00:00    ┆             ┆ 19:47:00    ┆ 21:58:00    ┆ 12:00:00    ┆ 12:00:00    │
│ 662152913    ┆ 2022-08-15  ┆ 1           ┆ 2022-08-15  ┆ 2022-08-16  ┆ 2022-08-15  ┆ 2022-08-15  │
│              ┆ 14:10:00    ┆             ┆ 16:45:00    ┆ 01:55:00    ┆ 14:10:00    ┆ 14:10:00    │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ 753558469    ┆ 2026-05-24  ┆ 2           ┆ 2026-05-24  ┆ 2026-05-24  ┆ 2026-05-24  ┆ 2026-05-25  │
│              ┆ 18:39:00    ┆             ┆ 18:39:00    ┆ 18:39:00    ┆ 18:40:00    ┆ 16:00:00    │
│ 753563196    ┆ 2026-05-25  ┆ 2           ┆ 2026-05-25  ┆ 2026-05-25  ┆ 2026-05-25  ┆ 2026-05-25  │
│              ┆ 04:49:00    ┆             ┆ 04:49:00    ┆ 04:49:00    ┆ 05:17:00    ┆ 08:00:00    │
│ 753573877    ┆ 2026-05-25  ┆ 1           ┆ 2026-05-25  ┆ 2026-05-26  ┆ 2026-05-25  ┆ 2026-05-25  │
│              ┆ 20:45:00    ┆             ┆ 21:53:00    ┆ 13:06:06    ┆ 20:45:00    ┆ 20:45:00    │
│ 753579730    ┆ 2026-05-25  ┆ 2           ┆ 2026-05-25  ┆ 2026-05-25  ┆ 2026-05-25  ┆ 2026-05-26  │
│              ┆ 23:23:00    ┆             ┆ 23:23:00    ┆ 23:23:00    ┆ 23:59:00    ┆ 23:01:00    │
│ 753665697    ┆ 2026-05-26  ┆ 1           ┆ 2026-05-26  ┆ 2026-05-26  ┆ 2026-05-26  ┆ 2026-05-27  │
│              ┆ 17:24:00    ┆             ┆ 17:24:00    ┆ 17:24:00    ┆ 17:42:00    ┆ 15:31:00    │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
# Maximum sepsis onset v3
df_sepsis_v3_maxonset = df_sepsis_v3.join(
    df_sepsis_v3.group_by("EncounterEpicCsn").agg(
    pl.col("sepsis_score").max().alias('max_sepsis_score')
    ),
	on='EncounterEpicCsn',
	how='inner'
).filter(
    pl.col("sepsis_score")==pl.col("max_sepsis_score")
).group_by(
    "EncounterEpicCsn", "max_sepsis_score"
).agg(
    pl.col("sepsis_instance").min().alias('sepsis_instant'),
    pl.col("infect_dt").min().alias('min_infect_dt'),
    pl.col("Event_DateTime").min().alias('min_Event_DateTime'),
).sort(by=["EncounterEpicCsn", 'sepsis_instant'])
df_sepsis_v3_maxonset

shape: (13_878, 5)
┌──────────────────┬──────────────────┬────────────────┬─────────────────────┬─────────────────────┐
│ EncounterEpicCsn ┆ max_sepsis_score ┆ sepsis_instant ┆ min_infect_dt       ┆ min_Event_DateTime  │
│ ---              ┆ ---              ┆ ---            ┆ ---                 ┆ ---                 │
│ i64              ┆ i32              ┆ datetime[μs]   ┆ datetime[μs]        ┆ datetime[μs]        │
╞══════════════════╪══════════════════╪════════════════╪═════════════════════╪═════════════════════╡
│ 659308243        ┆ 3                ┆ 2022-06-14     ┆ 2022-06-14 22:10:00 ┆ 2022-06-15 01:22:03 │
│                  ┆                  ┆ 22:10:00       ┆                     ┆                     │
│ 660956097        ┆ 3                ┆ 2022-06-28     ┆ 2022-06-28 06:10:00 ┆ 2022-06-28 03:59:07 │
│                  ┆                  ┆ 03:59:07       ┆                     ┆                     │
│ 661424247        ┆ 3                ┆ 2022-08-28     ┆ 2022-08-28 05:30:00 ┆ 2022-08-28 12:04:34 │
│                  ┆                  ┆ 05:30:00       ┆                     ┆                     │
│ 661471289        ┆ 2                ┆ 2022-06-07     ┆ 2022-06-07 19:47:00 ┆ 2022-06-07 12:00:00 │
│                  ┆                  ┆ 12:00:00       ┆                     ┆                     │
│ 662152913        ┆ 2                ┆ 2022-08-15     ┆ 2022-08-15 16:45:00 ┆ 2022-08-15 16:45:00 │
│                  ┆                  ┆ 16:45:00       ┆                     ┆                     │
│ …                ┆ …                ┆ …              ┆ …                   ┆ …                   │
│ 753558469        ┆ 3                ┆ 2026-05-25     ┆ 2026-05-25 19:43:52 ┆ 2026-05-27 12:24:00 │
│                  ┆                  ┆ 19:43:52       ┆                     ┆                     │
│ 753563196        ┆ 2                ┆ 2026-05-25     ┆ 2026-05-25 04:49:00 ┆ 2026-05-25 05:22:00 │
│                  ┆                  ┆ 04:49:00       ┆                     ┆                     │
│ 753573877        ┆ 1                ┆ 2026-05-25     ┆ 2026-05-25 21:53:00 ┆ 2026-05-25 20:45:00 │
│                  ┆                  ┆ 20:45:00       ┆                     ┆                     │
│ 753579730        ┆ 2                ┆ 2026-05-25     ┆ 2026-05-25 23:23:00 ┆ 2026-05-25 23:59:00 │
│                  ┆                  ┆ 23:23:00       ┆                     ┆                     │
│ 753665697        ┆ 1                ┆ 2026-05-26     ┆ 2026-05-26 17:24:00 ┆ 2026-05-26 17:42:00 │
│                  ┆                  ┆ 17:24:00       ┆                     ┆                     │
└──────────────────┴──────────────────┴────────────────┴─────────────────────┴─────────────────────┘

In [ ]:
# First sepsis onset v12
df_sepsis_v2_firstonset = df_sepsis_v2.join(
    df_sepsis_v2.group_by("EncounterEpicCsn").agg(
    pl.col("sepsis_instance").min().alias('first_sepsis_instant')
    ),
	on='EncounterEpicCsn',
	how='inner'
).filter(
    pl.col("sepsis_instance")==pl.col("first_sepsis_instant")
).group_by(
    "EncounterEpicCsn", "first_sepsis_instant"
).agg(
    pl.col("sepsis_score").max(),
    pl.col("infect_dt").min().alias('min_infect_dt'),
    pl.col("infect_dt").max().alias('max_infect_dt'),
    pl.col("Event_DateTime").min().alias('min_Event_DateTime'),
    pl.col("Event_DateTime").max().alias('max_Event_DateTime'),
).sort(by=["EncounterEpicCsn", 'first_sepsis_instant'])
df_sepsis_v2_firstonset

shape: (14_577, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ EncounterEpi ┆ first_sepsi ┆ sepsis_scor ┆ min_infect_ ┆ max_infect_ ┆ min_Event_D ┆ max_Event_D │
│ cCsn         ┆ s_instant   ┆ e           ┆ dt          ┆ dt          ┆ ateTime     ┆ ateTime     │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ i64          ┆ datetime[μs ┆ i32         ┆ datetime[μs ┆ datetime[μs ┆ datetime[μs ┆ datetime[μs │
│              ┆ ]           ┆             ┆ ]           ┆ ]           ┆ ]           ┆ ]           │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 659308243    ┆ 2022-06-14  ┆ 3           ┆ 2022-06-14  ┆ 2022-06-14  ┆ 2022-06-14  ┆ 2022-06-14  │
│              ┆ 17:52:00    ┆             ┆ 22:10:00    ┆ 22:10:00    ┆ 17:52:00    ┆ 17:52:00    │
│ 660956097    ┆ 2022-06-27  ┆ 1           ┆ 2022-06-28  ┆ 2022-06-28  ┆ 2022-06-27  ┆ 2022-06-27  │
│              ┆ 18:28:00    ┆             ┆ 06:10:00    ┆ 06:10:00    ┆ 18:28:00    ┆ 18:28:00    │
│ 661424247    ┆ 2022-08-28  ┆ 3           ┆ 2022-08-28  ┆ 2022-08-28  ┆ 2022-08-28  ┆ 2022-08-28  │
│              ┆ 02:18:00    ┆             ┆ 05:30:00    ┆ 05:30:00    ┆ 02:18:00    ┆ 02:18:00    │
│ 661471289    ┆ 2022-06-07  ┆ 2           ┆ 2022-06-07  ┆ 2022-06-07  ┆ 2022-06-07  ┆ 2022-06-07  │
│              ┆ 12:07:00    ┆             ┆ 19:47:00    ┆ 19:47:00    ┆ 12:07:00    ┆ 12:07:00    │
│ 662152913    ┆ 2022-08-15  ┆ 1           ┆ 2022-08-15  ┆ 2022-08-15  ┆ 2022-08-15  ┆ 2022-08-15  │
│              ┆ 14:10:00    ┆             ┆ 16:45:00    ┆ 16:45:00    ┆ 14:10:00    ┆ 14:10:00    │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ 753558469    ┆ 2026-05-24  ┆ 2           ┆ 2026-05-24  ┆ 2026-05-24  ┆ 2026-05-24  ┆ 2026-05-24  │
│              ┆ 18:39:00    ┆             ┆ 18:39:00    ┆ 18:39:00    ┆ 18:49:00    ┆ 18:54:00    │
│ 753563196    ┆ 2026-05-25  ┆ 1           ┆ 2026-05-25  ┆ 2026-05-25  ┆ 2026-05-25  ┆ 2026-05-25  │
│              ┆ 04:42:00    ┆             ┆ 04:49:00    ┆ 04:49:00    ┆ 04:42:00    ┆ 04:42:00    │
│ 753573877    ┆ 2026-05-25  ┆ 1           ┆ 2026-05-25  ┆ 2026-05-25  ┆ 2026-05-25  ┆ 2026-05-25  │
│              ┆ 16:27:00    ┆             ┆ 21:53:00    ┆ 21:53:00    ┆ 16:27:00    ┆ 16:27:00    │
│ 753579730    ┆ 2026-05-25  ┆ 2           ┆ 2026-05-25  ┆ 2026-05-25  ┆ 2026-05-25  ┆ 2026-05-26  │
│              ┆ 23:23:00    ┆             ┆ 23:23:00    ┆ 23:23:00    ┆ 23:59:00    ┆ 00:00:00    │
│ 753665697    ┆ 2026-05-26  ┆ 1           ┆ 2026-05-26  ┆ 2026-05-26  ┆ 2026-05-26  ┆ 2026-05-26  │
│              ┆ 15:40:17    ┆             ┆ 17:24:00    ┆ 17:24:00    ┆ 15:40:17    ┆ 15:40:17    │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [ ]:
# Maximum sepsis onset v2
df_sepsis_v2_maxonset = df_sepsis_v2.join(
    df_sepsis_v2.group_by("EncounterEpicCsn").agg(
    pl.col("sepsis_score").max().alias('max_sepsis_score')
    ),
	on='EncounterEpicCsn',
	how='inner'
).filter(
    pl.col("sepsis_score")==pl.col("max_sepsis_score")
).group_by(
    "EncounterEpicCsn", "max_sepsis_score"
).agg(
    pl.col("sepsis_instance").min().alias('sepsis_instant'),
    pl.col("infect_dt").min().alias('min_infect_dt'),
    pl.col("Event_DateTime").min().alias('min_Event_DateTime'),
).sort(by=["EncounterEpicCsn", 'sepsis_instant'])
df_sepsis_v2_maxonset

shape: (14_577, 5)
┌──────────────────┬──────────────────┬────────────────┬─────────────────────┬─────────────────────┐
│ EncounterEpicCsn ┆ max_sepsis_score ┆ sepsis_instant ┆ min_infect_dt       ┆ min_Event_DateTime  │
│ ---              ┆ ---              ┆ ---            ┆ ---                 ┆ ---                 │
│ i64              ┆ i32              ┆ datetime[μs]   ┆ datetime[μs]        ┆ datetime[μs]        │
╞══════════════════╪══════════════════╪════════════════╪═════════════════════╪═════════════════════╡
│ 659308243        ┆ 3                ┆ 2022-06-14     ┆ 2022-06-14 22:10:00 ┆ 2022-06-14 17:52:00 │
│                  ┆                  ┆ 17:52:00       ┆                     ┆                     │
│ 660956097        ┆ 3                ┆ 2022-06-28     ┆ 2022-06-28 06:10:00 ┆ 2022-06-28 01:09:00 │
│                  ┆                  ┆ 01:09:00       ┆                     ┆                     │
│ 661424247        ┆ 3                ┆ 2022-08-28     ┆ 2022-08-28 05:30:00 ┆ 2022-08-28 02:18:00 │
│                  ┆                  ┆ 02:18:00       ┆                     ┆                     │
│ 661471289        ┆ 2                ┆ 2022-06-07     ┆ 2022-06-07 19:47:00 ┆ 2022-06-07 12:07:00 │
│                  ┆                  ┆ 12:07:00       ┆                     ┆                     │
│ 662152913        ┆ 2                ┆ 2022-08-15     ┆ 2022-08-15 16:45:00 ┆ 2022-08-15 17:00:00 │
│                  ┆                  ┆ 16:45:00       ┆                     ┆                     │
│ …                ┆ …                ┆ …              ┆ …                   ┆ …                   │
│ 753558469        ┆ 2                ┆ 2026-05-24     ┆ 2026-05-24 18:39:00 ┆ 2026-05-24 18:54:00 │
│                  ┆                  ┆ 18:39:00       ┆                     ┆                     │
│ 753563196        ┆ 2                ┆ 2026-05-25     ┆ 2026-05-25 04:49:00 ┆ 2026-05-25 05:24:00 │
│                  ┆                  ┆ 04:49:00       ┆                     ┆                     │
│ 753573877        ┆ 1                ┆ 2026-05-25     ┆ 2026-05-25 21:53:00 ┆ 2026-05-25 16:27:00 │
│                  ┆                  ┆ 16:27:00       ┆                     ┆                     │
│ 753579730        ┆ 2                ┆ 2026-05-25     ┆ 2026-05-25 23:23:00 ┆ 2026-05-26 00:00:00 │
│                  ┆                  ┆ 23:23:00       ┆                     ┆                     │
│ 753665697        ┆ 1                ┆ 2026-05-26     ┆ 2026-05-26 17:24:00 ┆ 2026-05-26 15:40:17 │
│                  ┆                  ┆ 15:40:17       ┆                     ┆                     │
└──────────────────┴──────────────────┴────────────────┴─────────────────────┴─────────────────────┘

In [ ]:
# Focusing only on the encounter categorized by both v2 and v3
df_sepsis_v23_maxonset = df_sepsis_v2_maxonset.join(
    df_sepsis_v3_maxonset, on=['EncounterEpicCsn'], how='inner', suffix='_v3'
)
# df_sepsis_v23_maxonset
df_sepsis_v23_maxonset.filter(
    pl.col("max_sepsis_score_v3")!=pl.col("max_sepsis_score")
).sort(by=['EncounterEpicCsn'])

shape: (1_599, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ max_sepsi ┆ sepsis_in ┆ min_infec ┆ … ┆ max_sepsi ┆ sepsis_in ┆ min_infec ┆ min_Even │
│ EpicCsn   ┆ s_score   ┆ stant     ┆ t_dt      ┆   ┆ s_score_v ┆ stant_v3  ┆ t_dt_v3   ┆ t_DateTi │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 3         ┆ ---       ┆ ---       ┆ me_v3    │
│ i64       ┆ i32       ┆ datetime[ ┆ datetime[ ┆   ┆ ---       ┆ datetime[ ┆ datetime[ ┆ ---      │
│           ┆           ┆ μs]       ┆ μs]       ┆   ┆ i32       ┆ μs]       ┆ μs]       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662608744 ┆ 2         ┆ 2022-07-1 ┆ 2022-07-1 ┆ … ┆ 3         ┆ 2022-07-1 ┆ 2022-07-1 ┆ 2022-07- │
│           ┆           ┆ 3         ┆ 3         ┆   ┆           ┆ 3         ┆ 3         ┆ 14       │
│           ┆           ┆ 11:50:00  ┆ 11:50:00  ┆   ┆           ┆ 11:50:00  ┆ 11:50:00  ┆ 14:18:00 │
│ 662965478 ┆ 2         ┆ 2022-06-0 ┆ 2022-06-0 ┆ … ┆ 3         ┆ 2022-06-0 ┆ 2022-06-0 ┆ 2022-06- │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆ 1         ┆ 1         ┆ 01       │
│           ┆           ┆ 15:28:00  ┆ 15:28:00  ┆   ┆           ┆ 15:28:00  ┆ 15:28:00  ┆ 22:40:00 │
│ 663195289 ┆ 2         ┆ 2022-06-0 ┆ 2022-06-0 ┆ … ┆ 3         ┆ 2022-06-0 ┆ 2022-06-0 ┆ 2022-06- │
│           ┆           ┆ 6         ┆ 6         ┆   ┆           ┆ 6         ┆ 6         ┆ 07       │
│           ┆           ┆ 17:37:00  ┆ 17:54:00  ┆   ┆           ┆ 17:54:00  ┆ 17:54:00  ┆ 06:05:38 │
│ 663236716 ┆ 2         ┆ 2022-06-0 ┆ 2022-06-0 ┆ … ┆ 3         ┆ 2022-06-0 ┆ 2022-06-0 ┆ 2022-06- │
│           ┆           ┆ 7         ┆ 7         ┆   ┆           ┆ 7         ┆ 7         ┆ 08       │
│           ┆           ┆ 12:30:00  ┆ 14:44:00  ┆   ┆           ┆ 14:44:00  ┆ 14:44:00  ┆ 04:31:00 │
│ 663380959 ┆ 2         ┆ 2022-07-2 ┆ 2022-07-2 ┆ … ┆ 3         ┆ 2022-07-0 ┆ 2022-07-0 ┆ 2022-07- │
│           ┆           ┆ 1         ┆ 3         ┆   ┆           ┆ 6         ┆ 6         ┆ 06       │
│           ┆           ┆ 06:30:00  ┆ 06:26:00  ┆   ┆           ┆ 07:41:00  ┆ 07:41:00  ┆ 13:21:00 │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 752963510 ┆ 2         ┆ 2026-05-1 ┆ 2026-05-1 ┆ … ┆ 3         ┆ 2026-05-1 ┆ 2026-05-1 ┆ 2026-05- │
│           ┆           ┆ 6         ┆ 6         ┆   ┆           ┆ 6         ┆ 6         ┆ 16       │
│           ┆           ┆ 07:15:00  ┆ 08:32:00  ┆   ┆           ┆ 08:32:00  ┆ 08:32:00  ┆ 13:12:00 │
│ 753052938 ┆ 2         ┆ 2026-05-1 ┆ 2026-05-1 ┆ … ┆ 3         ┆ 2026-05-1 ┆ 2026-05-1 ┆ 2026-05- │
│           ┆           ┆ 6         ┆ 6         ┆   ┆           ┆ 6         ┆ 6         ┆ 16       │
│           ┆           ┆ 12:12:00  ┆ 12:12:00  ┆   ┆           ┆ 12:12:00  ┆ 12:12:00  ┆ 14:20:28 │
│ 753371509 ┆ 2         ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ 3         ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05- │
│           ┆           ┆ 1         ┆ 1         ┆   ┆           ┆ 1         ┆ 1         ┆ 21       │
│           ┆           ┆ 05:49:00  ┆ 05:49:00  ┆   ┆           ┆ 05:49:00  ┆ 05:49:00  ┆ 18:03:23 │
│ 753466755 ┆ 2         ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ 3         ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05- │
│           ┆           ┆ 2         ┆ 2         ┆   ┆           ┆ 2         ┆ 2         ┆ 22       │
│           ┆           ┆ 07:41:00  ┆ 07:41:00  ┆   ┆           ┆ 07:41:00  ┆ 07:41:00  ┆ 09:51:41 │
│ 753558469 ┆ 2         ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ 3         ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05- │
│           ┆           ┆ 4         ┆ 4         ┆   ┆           ┆ 5         ┆ 5         ┆ 27       │
│           ┆           ┆ 18:39:00  ┆ 18:39:00  ┆   ┆           ┆ 19:43:52  ┆ 19:43:52  ┆ 12:24:00 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df_sepsis_v23_maxonset.with_columns(
    (pl.col("max_sepsis_score_v3")-pl.col("max_sepsis_score")).alias('diff_sepsis_score_v3-v2')
).filter(
    pl.col("diff_sepsis_score_v3-v2")<0
)

shape: (389, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ max_sepsi ┆ sepsis_in ┆ min_infec ┆ … ┆ sepsis_in ┆ min_infec ┆ min_Event ┆ diff_sep │
│ EpicCsn   ┆ s_score   ┆ stant     ┆ t_dt      ┆   ┆ stant_v3  ┆ t_dt_v3   ┆ _DateTime ┆ sis_scor │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ _v3       ┆ e_v3-v2  │
│ i64       ┆ i32       ┆ datetime[ ┆ datetime[ ┆   ┆ datetime[ ┆ datetime[ ┆ ---       ┆ ---      │
│           ┆           ┆ μs]       ┆ μs]       ┆   ┆ μs]       ┆ μs]       ┆ datetime[ ┆ i32      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 663740518 ┆ 2         ┆ 2022-07-0 ┆ 2022-07-0 ┆ … ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ -1       │
│           ┆           ┆ 6         ┆ 8         ┆   ┆ 6         ┆ 6         ┆ 6         ┆          │
│           ┆           ┆ 20:56:00  ┆ 20:54:36  ┆   ┆ 09:34:00  ┆ 09:37:00  ┆ 09:34:00  ┆          │
│ 663941695 ┆ 2         ┆ 2022-06-2 ┆ 2022-06-2 ┆ … ┆ 2022-06-2 ┆ 2022-06-2 ┆ 2022-06-2 ┆ -1       │
│           ┆           ┆ 7         ┆ 9         ┆   ┆ 1         ┆ 1         ┆ 2         ┆          │
│           ┆           ┆ 06:00:00  ┆ 05:28:00  ┆   ┆ 21:05:00  ┆ 21:05:00  ┆ 05:00:00  ┆          │
│ 664242978 ┆ 3         ┆ 2022-07-1 ┆ 2022-07-1 ┆ … ┆ 2022-06-2 ┆ 2022-06-2 ┆ 2022-07-1 ┆ -1       │
│           ┆           ┆ 5         ┆ 7         ┆   ┆ 7         ┆ 7         ┆ 2         ┆          │
│           ┆           ┆ 23:00:00  ┆ 16:59:00  ┆   ┆ 10:03:00  ┆ 10:03:00  ┆ 05:59:00  ┆          │
│ 664261442 ┆ 3         ┆ 2022-07-0 ┆ 2022-07-0 ┆ … ┆ 2022-06-2 ┆ 2022-06-2 ┆ 2022-06-3 ┆ -1       │
│           ┆           ┆ 6         ┆ 7         ┆   ┆ 9         ┆ 9         ┆ 0         ┆          │
│           ┆           ┆ 19:16:00  ┆ 14:29:00  ┆   ┆ 21:24:00  ┆ 21:24:00  ┆ 00:17:00  ┆          │
│ 664529709 ┆ 2         ┆ 2022-07-0 ┆ 2022-07-0 ┆ … ┆ 2022-07-0 ┆ 2022-07-0 ┆ 2022-07-0 ┆ -1       │
│           ┆           ┆ 1         ┆ 1         ┆   ┆ 1         ┆ 1         ┆ 1         ┆          │
│           ┆           ┆ 14:18:00  ┆ 14:18:00  ┆   ┆ 14:10:00  ┆ 14:18:00  ┆ 14:10:00  ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 749212782 ┆ 3         ┆ 2026-03-2 ┆ 2026-03-2 ┆ … ┆ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ -1       │
│           ┆           ┆ 5         ┆ 5         ┆   ┆ 4         ┆ 5         ┆ 4         ┆          │
│           ┆           ┆ 15:07:00  ┆ 15:07:00  ┆   ┆ 23:26:00  ┆ 01:30:00  ┆ 23:26:00  ┆          │
│ 749957663 ┆ 3         ┆ 2026-04-0 ┆ 2026-04-0 ┆ … ┆ 2026-04-2 ┆ 2026-04-2 ┆ 2026-04-2 ┆ -2       │
│           ┆           ┆ 3         ┆ 4         ┆   ┆ 5         ┆ 6         ┆ 5         ┆          │
│           ┆           ┆ 20:12:00  ┆ 16:01:44  ┆   ┆ 20:44:00  ┆ 16:04:00  ┆ 20:44:00  ┆          │
│ 751015083 ┆ 3         ┆ 2026-04-1 ┆ 2026-04-1 ┆ … ┆ 2026-04-2 ┆ 2026-04-2 ┆ 2026-04-2 ┆ -1       │
│           ┆           ┆ 7         ┆ 8         ┆   ┆ 1         ┆ 3         ┆ 1         ┆          │
│           ┆           ┆ 23:16:00  ┆ 23:51:00  ┆   ┆ 14:00:00  ┆ 13:33:00  ┆ 14:00:00  ┆          │
│ 752058410 ┆ 2         ┆ 2026-05-0 ┆ 2026-05-0 ┆ … ┆ 2026-05-0 ┆ 2026-05-0 ┆ 2026-05-0 ┆ -1       │
│           ┆           ┆ 3         ┆ 3         ┆   ┆ 3         ┆ 3         ┆ 3         ┆          │
│           ┆           ┆ 12:24:00  ┆ 13:47:00  ┆   ┆ 11:24:00  ┆ 13:47:00  ┆ 11:24:00  ┆          │
│ 752357807 ┆ 2         ┆ 2026-05-0 ┆ 2026-05-0 ┆ … ┆ 2026-05-0 ┆ 2026-05-0 ┆ 2026-05-0 ┆ -1       │
│           ┆           ┆ 6         ┆ 6         ┆   ┆ 6         ┆ 6         ┆ 6         ┆          │
│           ┆           ┆ 17:03:00  ┆ 17:03:00  ┆   ┆ 17:03:00  ┆ 17:03:00  ┆ 17:12:00  ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# Focusing only on the encounter categorized by both v2 and v3 in the maxonset
df_sepsis_v23_firstonset = df_sepsis_v2_firstonset.join(
    df_sepsis_v3_firstonset, on=['EncounterEpicCsn'], how='inner', suffix='_v3'
)
# df_sepsis_v23_firstonset
df_sepsis_v23_firstonset.filter(
    pl.col("sepsis_score_v3")!=pl.col("sepsis_score")
).sort(by=['EncounterEpicCsn'])

df_sepsis_v23_firstonset.with_columns(
    (pl.col("sepsis_score_v3")-pl.col("sepsis_score")).alias('diff_sepsis_score_v3-v2')
)['diff_sepsis_score_v3-v2'].value_counts(sort=True)

df_sepsis_v23_firstonset.with_columns(
    (pl.col("sepsis_score_v3")-pl.col("sepsis_score")).alias('diff_sepsis_score_v3-v2')
).filter(
	pl.col('diff_sepsis_score_v3-v2')<0
)

enc_shock_v2_and_noshock_v3 = df_sepsis_v23_firstonset.filter(
    (pl.col("sepsis_score_v3")<3) & (pl.col("sepsis_score")==3)
)['EncounterEpicCsn'].unique()

In [ ]:
df_sepsis_v23_maxonset.filter(
    pl.col("EncounterEpicCsn").is_in([662715699, 662358356])
)

shape: (2, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ max_sepsi ┆ sepsis_in ┆ min_infec ┆ … ┆ max_sepsi ┆ sepsis_in ┆ min_infec ┆ min_Even │
│ EpicCsn   ┆ s_score   ┆ stant     ┆ t_dt      ┆   ┆ s_score_v ┆ stant_v3  ┆ t_dt_v3   ┆ t_DateTi │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ 3         ┆ ---       ┆ ---       ┆ me_v3    │
│ i64       ┆ i32       ┆ datetime[ ┆ datetime[ ┆   ┆ ---       ┆ datetime[ ┆ datetime[ ┆ ---      │
│           ┆           ┆ μs]       ┆ μs]       ┆   ┆ i32       ┆ μs]       ┆ μs]       ┆ datetime │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662358356 ┆ 3         ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ 3         ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06- │
│           ┆           ┆ 3         ┆ 3         ┆   ┆           ┆ 3         ┆ 3         ┆ 13       │
│           ┆           ┆ 04:59:00  ┆ 04:59:00  ┆   ┆           ┆ 04:59:00  ┆ 04:59:00  ┆ 05:21:00 │
│ 662715699 ┆ 3         ┆ 2022-06-2 ┆ 2022-06-3 ┆ … ┆ 3         ┆ 2022-07-0 ┆ 2022-07-0 ┆ 2022-07- │
│           ┆           ┆ 9         ┆ 0         ┆   ┆           ┆ 1         ┆ 3         ┆ 01       │
│           ┆           ┆ 11:02:00  ┆ 20:59:00  ┆   ┆           ┆ 22:00:00  ┆ 10:47:00  ┆ 22:00:00 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df_all_v3.filter(
    pl.col("EncounterEpicCsn").is_in([662715699])&
	(pl.col("Event_DateTime") == (dt.datetime(2022, 7, 1, 11)))&
	# (pl.col("Event_DateTime") >= (dt.datetime(2022, 7, 1, 11)-dt.timedelta(hours=48)))&
	# (pl.col("Event_DateTime") <= (dt.datetime(2022, 7, 1, 11)+dt.timedelta(hours=48)))&
	# (pl.col("Event_Grouper").str.to_lowercase().str.starts_with('Glasgow Coma Score'))
	(pl.col("Event_Grouper") == 'Glasgow Coma Score')
)

shape: (1, 52)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ Immunocro ┆ CKD_Dialy ┆ Solid_Org ┆ Pregnanc │
│ EpicCsn   ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ mpromised ┆ sis_Regis ┆ an_Transp ┆ y_Regist │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ _Registry ┆ try_YN    ┆ lant_Regi ┆ ry_YN    │
│ i64       ┆ datetime[ ┆           ┆ str       ┆   ┆ _YN       ┆ ---       ┆ str…      ┆ ---      │
│           ┆ μs]       ┆           ┆           ┆   ┆ ---       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-07-0 ┆ Flowsheet ┆ Glasgow   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 1         ┆           ┆ Coma      ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:00:00  ┆           ┆ Score     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df_o2vent_3.filter(
    pl.col("EncounterEpicCsn").is_in([662715699])&
	(pl.col("Event_DateTime") >= (dt.datetime(2022, 7, 1, 11)-dt.timedelta(hours=48)))&
	(pl.col("Event_DateTime") <= (dt.datetime(2022, 7, 1, 11)+dt.timedelta(hours=48)))&
	(pl.col("pulmonary_dysfunction_flag")==1)
)

shape: (15, 59)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ vent_doc_ ┆ o2_vent_f ┆ vent_end_ ┆ pulmonar │
│ EpicCsn   ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ flag      ┆ lag       ┆ flag      ┆ y_dysfun │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ction_fl │
│ i64       ┆ datetime[ ┆           ┆ str       ┆   ┆ i32       ┆ i32       ┆ i32       ┆ ag       │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-06-3 ┆ Lab       ┆ PAO2      ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 0         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 21:05:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ Flowsheet ┆ Vent      ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 2         ┆           ┆ On/Off    ┆   ┆           ┆           ┆           ┆          │
│           ┆ 08:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ Lab       ┆ PAO2      ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 2         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 16:16:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ Lab       ┆ PAO2      ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 2         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 02:18:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ Lab       ┆ PAO2      ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 2         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 02:18:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 662715699 ┆ 2022-06-2 ┆ Lab       ┆ PAO2      ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 9         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 21:07:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ Flowsheet ┆ Vent      ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 2         ┆           ┆ On/Off    ┆   ┆           ┆           ┆           ┆          │
│           ┆ 04:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Flowsheet ┆ Vent      ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 9         ┆           ┆ On/Off    ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:15:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-3 ┆ Flowsheet ┆ Vent      ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 0         ┆           ┆ On/Off    ┆   ┆           ┆           ┆           ┆          │
│           ┆ 03:05:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Flowsheet ┆ Vent      ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 9         ┆           ┆ On/Off    ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:05:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df_all_v3.filter(
    pl.col("EncounterEpicCsn").is_in([662715699])&
	# (pl.col("Event_DateTime") >= (dt.datetime(2022, 7, 1, 11)-dt.timedelta(hours=48)))&
	# (pl.col("Event_DateTime") <= (dt.datetime(2022, 7, 1, 11)+dt.timedelta(hours=48)))&
	(pl.col("Event_Grouper") == 'Lactate')
).sort(by='Event_DateTime')

shape: (13, 52)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ Immunocro ┆ CKD_Dialy ┆ Solid_Org ┆ Pregnanc │
│ EpicCsn   ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ mpromised ┆ sis_Regis ┆ an_Transp ┆ y_Regist │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ _Registry ┆ try_YN    ┆ lant_Regi ┆ ry_YN    │
│ i64       ┆ datetime[ ┆           ┆ str       ┆   ┆ _YN       ┆ ---       ┆ str…      ┆ ---      │
│           ┆ μs]       ┆           ┆           ┆   ┆ ---       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-06-2 ┆ Lab       ┆ Lactate   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:02:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Lab       ┆ Lactate   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 12:15:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Lab       ┆ Lactate   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 13:12:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Lab       ┆ Lactate   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 13:54:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Procedure ┆ Lactate   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆ Order     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 15:49:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 662715699 ┆ 2022-07-0 ┆ Procedure ┆ Lactate   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 1         ┆ Order     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 21:01:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ Lab       ┆ Lactate   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 1         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 21:09:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ Procedure ┆ Lactate   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 2         ┆ Order     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 02:43:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ Lab       ┆ Lactate   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 2         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 02:44:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ Procedure ┆ Lactate   ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 3         ┆ Order     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10:57:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df_organdysf_3.filter(
    pl.col("EncounterEpicCsn").is_in([662715699])&
	(pl.col("Event_DateTime") == (dt.datetime(2022, 7, 1, 11)))&
	# (pl.col("Event_DateTime") >= (dt.datetime(2022, 7, 1, 11)-dt.timedelta(hours=48)))&
	# (pl.col("Event_DateTime") <= (dt.datetime(2022, 7, 1, 11)+dt.timedelta(hours=48)))&
    (pl.col("organ_dysfunction_total")>0) 
)

shape: (1, 38)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ last_temp ┆ last_puls ┆ … ┆ renal_fai ┆ hepatic_f ┆ neurologi ┆ organ_dy │
│ EpicCsn   ┆ eTime     ┆ _8h       ┆ e_8h      ┆   ┆ lure_flag ┆ ailure_fl ┆ cal_failu ┆ sfunctio │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ag        ┆ re_flag   ┆ n_total  │
│ i64       ┆ datetime[ ┆ f64       ┆ f64       ┆   ┆ i32       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆ i32       ┆ i64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-07-0 ┆ 99.9      ┆ 89.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df_shock_3.filter(
    pl.col("EncounterEpicCsn").is_in([662715699])&
	(pl.col("Event_DateTime") >= (dt.datetime(2022, 7, 1, 22, 2)-dt.timedelta(hours=48)))&
	(pl.col("Event_DateTime") <= (dt.datetime(2022, 7, 1, 22, 2)+dt.timedelta(hours=48)))
).sort(by=['Event_DateTime'])

shape: (295, 44)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ last_temp ┆ last_puls ┆ … ┆ map65_fla ┆ lactate4_ ┆ vasopress ┆ septic_s │
│ EpicCsn   ┆ eTime     ┆ _8h       ┆ e_8h      ┆   ┆ g         ┆ flag      ┆ or_flag   ┆ hock_fla │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ g        │
│ i64       ┆ datetime[ ┆ f64       ┆ f64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ ---      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-06-2 ┆ 97.3      ┆ 66.0      ┆ … ┆ 0         ┆ null      ┆ 1         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.3      ┆ 66.0      ┆ … ┆ 0         ┆ null      ┆ 1         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:05:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.3      ┆ 66.0      ┆ … ┆ 0         ┆ null      ┆ 1         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:26:35  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-3 ┆ 97.3      ┆ 68.0      ┆ … ┆ 0         ┆ null      ┆ 1         ┆ 0        │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 00:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-3 ┆ 97.3      ┆ 68.0      ┆ … ┆ 0         ┆ null      ┆ 1         ┆ 0        │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 01:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 662715699 ┆ 2022-07-0 ┆ 100.4     ┆ 58.0      ┆ … ┆ 0         ┆ null      ┆ 1         ┆ 0        │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:36:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ 100.4     ┆ 58.0      ┆ … ┆ 0         ┆ null      ┆ 1         ┆ 0        │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:40:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ 100.4     ┆ 61.0      ┆ … ┆ 0         ┆ null      ┆ 1         ┆ 0        │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 21:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ 100.4     ┆ 61.0      ┆ … ┆ 0         ┆ null      ┆ 1         ┆ 0        │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 21:39:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ 100.4     ┆ 59.0      ┆ … ┆ 0         ┆ null      ┆ 1         ┆ 0        │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df_sirs_2

shape: (4_244, 57)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ Temp_Abno ┆ Resp_Rate ┆ Pule_High ┆ sirs_sco │
│ EpicCsn   ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ rmal_Flag ┆ _High_Fla ┆ _Flag     ┆ re       │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ g         ┆ ---       ┆ ---      │
│ i64       ┆ datetime[ ┆           ┆ str       ┆   ┆ i32       ┆ ---       ┆ i32       ┆ i32      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆ i32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-06-0 ┆ Diagnosis ┆ Encounter ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 2 01:53:0 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6.913     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Flowsheet ┆ Pulse     ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Flowsheet ┆ Respirati ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆ ons       ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Flowsheet ┆ Blood     ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆ Pressure  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Flowsheet ┆ Weight    ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 662715699 ┆ 2022-07-2 ┆ Diagnosis ┆ Billing   ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 4        │
│           ┆ 6 02:38:2 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6.133     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ Diagnosis ┆ Billing   ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 4        │
│           ┆ 6 02:38:2 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6.133     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ Diagnosis ┆ Billing   ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 4        │
│           ┆ 6 02:38:2 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6.133     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ Diagnosis ┆ Billing   ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 4        │
│           ┆ 8 02:18:3 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2.420     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ Diagnosis ┆ Billing   ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 4        │
│           ┆ 8 02:18:3 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2.420     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df_organdysf_2.filter(
	(pl.col("EncounterEpicCsn") == 662715699)&
	(pl.col("Event_DateTime") = (dt.datetime(2022, 6, 29, 11, 2)))
)

shape: (2_074, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ last_temp ┆ last_puls ┆ … ┆ renal_fai ┆ hepatic_f ┆ neurologi ┆ organ_dy │
│ EpicCsn   ┆ eTime     ┆ _8h       ┆ e_8h      ┆   ┆ lure_flag ┆ ailure_fl ┆ cal_failu ┆ sfunctio │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ag        ┆ re_flag   ┆ n_total  │
│ i64       ┆ datetime[ ┆ f64       ┆ f64       ┆   ┆ i32       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆ i32       ┆ i64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:02:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 12:10:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 12:15:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 13:12:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 13:54:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 662715699 ┆ 2022-07-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 5 01:46:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 5.110     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 6 02:38:2 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6.133     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 6 02:38:2 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6.133     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 8 02:18:3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2.420     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 8 02:18:3 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2.420     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [42]:
df_sirs_2.filter(
	(pl.col("EncounterEpicCsn") == 662715699)&
	(pl.col("Event_DateTime") <= (dt.datetime(2022, 6, 29, 11, 2)))&
	(pl.col("Event_DateTime") >= (dt.datetime(2022, 6, 29, 11, 2))-dt.timedelta(hours=6))&
	(pl.col("Event_Grouper")=='Lactate')
	# pl.col()
	# (pl.col("Event_DateTime") >= (dt.datetime(2022, 6, 29, 11, 2)-dt.timedelta(hours=48)))&
	# (pl.col("Event_DateTime") <= (dt.datetime(2022, 6, 29, 11, 2)+dt.timedelta(hours=48)))
)

shape: (4, 57)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ Temp_Abno ┆ Resp_Rate ┆ Pule_High ┆ sirs_sco │
│ EpicCsn   ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ rmal_Flag ┆ _High_Fla ┆ _Flag     ┆ re       │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ g         ┆ ---       ┆ ---      │
│ i64       ┆ datetime[ ┆           ┆ str       ┆   ┆ i32       ┆ ---       ┆ i32       ┆ i32      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆ i32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-06-2 ┆ Lab       ┆ Lactate   ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 1        │
│           ┆ 9         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 07:59:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Lab       ┆ Lactate   ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 1        │
│           ┆ 9         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 09:21:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Lab       ┆ Lactate   ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 1        │
│           ┆ 9         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10:23:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Lab       ┆ Lactate   ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 1        │
│           ┆ 9         ┆ Results   ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:02:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [44]:
df_sirs_3.filter(
    	(pl.col("EncounterEpicCsn") == 662715699)&
	(pl.col("Event_DateTime") <= (dt.datetime(2022, 6, 29, 11, 2)))&
	(pl.col("Event_DateTime") >= (dt.datetime(2022, 6, 29, 11, 2))-dt.timedelta(hours=6))
	# (pl.col("Event_Grouper")=='Lactate')
)

shape: (5, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ last_temp ┆ last_puls ┆ … ┆ Pule_High ┆ Resp_Rate ┆ WBC_Abnor ┆ sirs_sco │
│ EpicCsn   ┆ eTime     ┆ _8h       ┆ e_8h      ┆   ┆ _Flag     ┆ _High_Fla ┆ mal_Flag  ┆ re       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ g         ┆ ---       ┆ ---      │
│ i64       ┆ datetime[ ┆ f64       ┆ f64       ┆   ┆ i32       ┆ ---       ┆ i32       ┆ i32      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆ i32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 09:21:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:02:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10:23:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 07:59:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
df_organdysf_2.filter(
	(pl.col("EncounterEpicCsn") == 662715699)&
	(pl.col("Event_DateTime") >= (dt.datetime(2022, 6, 29, 11, 2)-dt.timedelta(hours=48)))&
	(pl.col("Event_DateTime") <= (dt.datetime(2022, 6, 29, 11, 2)+dt.timedelta(hours=48)))&
	(pl.col("organ_dysfunction_total")>0)
).sort(by=['Event_DateTime'])

shape: (165, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ last_temp ┆ last_puls ┆ … ┆ renal_fai ┆ hepatic_f ┆ neurologi ┆ organ_dy │
│ EpicCsn   ┆ eTime     ┆ _8h       ┆ e_8h      ┆   ┆ lure_flag ┆ ailure_fl ┆ cal_failu ┆ sfunctio │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ag        ┆ re_flag   ┆ n_total  │
│ i64       ┆ datetime[ ┆ f64       ┆ f64       ┆   ┆ i32       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆ i32       ┆ i64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:02:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 13:12:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 97.6      ┆ 72.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 13:54:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 14:51:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 96.3      ┆ 89.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 14:55:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 662715699 ┆ 2022-07-0 ┆ 99.5      ┆ 88.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 08:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ 99.5      ┆ 87.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 08:22:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ 99.5      ┆ 87.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 09:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ 99.5      ┆ 88.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-0 ┆ 99.5      ┆ 89.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 1         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [28]:
df_shock_3.filter(
	(pl.col("EncounterEpicCsn") == 662715699)&
	(pl.col("Event_DateTime") >= (dt.datetime(2022, 6, 29, 11, 2)-dt.timedelta(hours=48)))&
	(pl.col("Event_DateTime") <= (dt.datetime(2022, 6, 29, 11, 2)+dt.timedelta(hours=48)))&
	(pl.col("septic_shock_flag")==1)
)

shape: (60, 44)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ last_temp ┆ last_puls ┆ … ┆ map65_fla ┆ lactate4_ ┆ vasopress ┆ septic_s │
│ EpicCsn   ┆ eTime     ┆ _8h       ┆ e_8h      ┆   ┆ g         ┆ flag      ┆ or_flag   ┆ hock_fla │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ g        │
│ i64       ┆ datetime[ ┆ f64       ┆ f64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ ---      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-06-2 ┆ 96.6      ┆ 85.0      ┆ … ┆ 1         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 15:55:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 96.6      ┆ 86.0      ┆ … ┆ 1         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 16:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 96.6      ┆ 86.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 16:05:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 96.6      ┆ 86.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 16:08:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ 96.6      ┆ 88.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 16:10:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 662715699 ┆ 2022-06-3 ┆ 98.4      ┆ 69.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 07:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-3 ┆ 98.4      ┆ 69.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 07:40:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-3 ┆ 98.2      ┆ 69.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 08:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-3 ┆ 98.2      ┆ 69.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 09:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-3 ┆ 98.2      ┆ 69.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 09:25:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [19]:
df_sirs_2_enc = df_sirs_2.filter(	
	pl.col("EncounterEpicCsn") == 662715699
)
df_sirs_2_enc

shape: (4_244, 57)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ Temp_Abno ┆ Resp_Rate ┆ Pule_High ┆ sirs_sco │
│ EpicCsn   ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ rmal_Flag ┆ _High_Fla ┆ _Flag     ┆ re       │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ g         ┆ ---       ┆ ---      │
│ i64       ┆ datetime[ ┆           ┆ str       ┆   ┆ i32       ┆ ---       ┆ i32       ┆ i32      │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆ i32       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 662715699 ┆ 2022-06-0 ┆ Diagnosis ┆ Encounter ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 2 01:53:0 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6.913     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Flowsheet ┆ Pulse     ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Flowsheet ┆ Respirati ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆ ons       ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Flowsheet ┆ Blood     ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆ Pressure  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-06-2 ┆ Flowsheet ┆ Weight    ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 1        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:14:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 662715699 ┆ 2022-07-2 ┆ Diagnosis ┆ Billing   ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 4        │
│           ┆ 6 02:38:2 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6.133     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ Diagnosis ┆ Billing   ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 4        │
│           ┆ 6 02:38:2 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6.133     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ Diagnosis ┆ Billing   ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 4        │
│           ┆ 6 02:38:2 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 6.133     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ Diagnosis ┆ Billing   ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 4        │
│           ┆ 8 02:18:3 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2.420     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 662715699 ┆ 2022-07-2 ┆ Diagnosis ┆ Billing   ┆ … ┆ 1         ┆ 1         ┆ 1         ┆ 4        │
│           ┆ 8 02:18:3 ┆ Event     ┆ Diagnosis ┆   ┆           ┆           ┆           ┆          │
│           ┆ 2.420     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Combine Organ dysfunctino and Pulmonary dysfunction into one dataframe

In [17]:
df_o2vent_3_cols = ['EncounterEpicCsn', "Event_DateTime"] + [c for c in df_o2vent_3.columns if c.endswith('_flag') or c.startswith('last_') or c.endswith('_score') or c.endswith('_ratio')]
df_o2vent_3_cols

['EncounterEpicCsn',
 'Event_DateTime',
 'pf_ratio',
 'vent_onoff_flag',
 'vent_doc_flag',
 'o2_vent_flag',
 'vent_end_flag',
 'pulmonary_dysfunction_flag']

In [18]:
df_o2vent_3_refined = df_o2vent_3.filter(
	# Remove rows where all the following columns are nulls
    # ~pl.all_horizontal(
    #     pl.col([
    #         'pf_ratio',	'PF_Ratio_Flag', 'vent_onoff_flag',	'vent_doc_flag', 'o2_vent_flag', 'vent_end_flag', 'pulmonary_dysfunction_flag'
	# 	]).is_null()
	# )

	pl.col("pulmonary_dysfunction_flag")>0

).select(df_o2vent_3_cols).unique(subset=['EncounterEpicCsn', 'Event_DateTime'])

In [20]:
df_organdysf_3_refined =df_organdysf_3.filter(
    pl.col("organ_dysfunction_total")>0
).select(
	['EncounterEpicCsn', 'Event_DateTime']+[c for c in df_organdysf_3.columns if c.endswith('_flag') or c.startswith('last_') or c.endswith('_score') or c.endswith('_ratio')]+['organ_dysfunction_total']
).unique(subset=['EncounterEpicCsn', 'Event_DateTime'])

In [21]:
df_organdysfunction_backbone = pl.concat([
    df_organdysf_3_refined.select("EncounterEpicCsn", "Event_DateTime", pl.lit("organdys").alias("organdysfunction_type")),
    df_o2vent_3_refined.select("EncounterEpicCsn", "Event_DateTime", pl.lit("pulmonary").alias("organdysfunction_type"))
], how='vertical')

In [22]:
df_organ_pulmonary_3 = df_organdysfunction_backbone.join(
    df_organdysf_3_refined, on=['EncounterEpicCsn', 'Event_DateTime'], how='left'
).join(df_o2vent_3_refined, on=['EncounterEpicCsn', 'Event_DateTime'], how='left').sort(by=['EncounterEpicCsn', 'Event_DateTime'])

### Combine flag dataframes with sepsis dataframes to map the cause v3

In [23]:
df_organ_pulmonary_3

shape: (4_363_739, 37)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ organdysf ┆ last_temp ┆ … ┆ vent_doc_ ┆ o2_vent_f ┆ vent_end_ ┆ pulmonar │
│ EpicCsn   ┆ eTime     ┆ unction_t ┆ _8h       ┆   ┆ flag      ┆ lag       ┆ flag      ┆ y_dysfun │
│ ---       ┆ ---       ┆ ype       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ction_fl │
│ i64       ┆ datetime[ ┆ ---       ┆ f64       ┆   ┆ i32       ┆ i32       ┆ i32       ┆ ag       │
│           ┆ μs]       ┆ str       ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 659308243 ┆ 2022-06-1 ┆ organdys  ┆ 98.2      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 16:40:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ organdys  ┆ 98.2      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 17:52:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ organdys  ┆ 98.2      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 18:48:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ organdys  ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 21:35:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ organdys  ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 21:49:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 753579730 ┆ 2026-05-2 ┆ organdys  ┆ 98.8      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 09:01:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 753579730 ┆ 2026-05-2 ┆ organdys  ┆ 98.8      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 753579730 ┆ 2026-05-2 ┆ organdys  ┆ 98.8      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10:13:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 753579730 ┆ 2026-05-2 ┆ organdys  ┆ 98.8      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10:19:04  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 753579730 ┆ 2026-05-2 ┆ organdys  ┆ 98.8      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 6         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

#### Combining septic shock flags with sepsis dataframe

In [24]:
df_sepsis_3_with_shock = df_sepsis_v3.join(
    df_shock_3, on=['EncounterEpicCsn', 'Event_DateTime'], how='left'
).filter(
    pl.col('sepsis_score') == 3
)

df_sepsis_3_with_shock = df_sepsis_3_with_shock.drop([c for c in df_sepsis_3_with_shock.columns if c.endswith('_right')])
# df_sepsis_3_with_shock = df_sepsis_3_with_shock.join(
#     df_o2vent_3.filter(
#     pl.col("pulmonary_dysfunction_flag") == 1
# 	).select(["EncounterEpicCsn", 'Event_DateTime', 'pf_ratio']+[c for c in df_o2vent_3.columns if c.endswith('_flag')]),
#     on='EncounterEpicCsn', how='left'
# )

# df_sepsis_3_with_shock = df_sepsis_3_with_shock.join(
#     df_organ_pulmonary_3.filter(
#     	(pl.col("pulmonary_dysfunction_flag") == 1)|(pl.col("organ_dysfunction_total")>0)
# 	).select(["EncounterEpicCsn", 'Event_DateTime', 'pf_ratio']+[c for c in df_o2vent_3.columns if c.endswith('_flag')]),
#     on='EncounterEpicCsn', how='left'
# )

df_shock_orgrandysfunction_3 = df_sepsis_3_with_shock.join_asof(
	df_organ_pulmonary_3,
	left_on='sepsis_instance',
	right_on='Event_DateTime',
	by='EncounterEpicCsn',
	strategy='nearest',
    suffix='_organdysfunction'
)

/tmp/ipykernel_1784179/789479857.py:22: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  df_shock_orgrandysfunction_3 = df_sepsis_3_with_shock.join_asof(

In [25]:
df_shock_orgrandysfunction_3

shape: (737_854, 83)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ infect_dt ┆ Event_Dat ┆ sepsis_in ┆ … ┆ vent_doc_ ┆ o2_vent_f ┆ vent_end_ ┆ pulmonar │
│ EpicCsn   ┆ ---       ┆ eTime     ┆ stance    ┆   ┆ flag      ┆ lag       ┆ flag      ┆ y_dysfun │
│ ---       ┆ datetime[ ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ction_fl │
│ i64       ┆ μs]       ┆ datetime[ ┆ datetime[ ┆   ┆ i32       ┆ i32       ┆ i32       ┆ ag       │
│           ┆           ┆ μs]       ┆ μs]       ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆ 6         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 03:33:00  ┆ 22:10:00  ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆ 6 02:50:2 ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 7.320     ┆ 22:10:00  ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆ 5         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 01:45:00  ┆ 22:10:00  ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆ 5         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 02:00:00  ┆ 22:10:00  ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆ 5         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 02:03:00  ┆ 22:10:00  ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:43:52  ┆ 17:00:00  ┆ 19:43:52  ┆   ┆           ┆           ┆           ┆          │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:43:52  ┆ 17:15:00  ┆ 19:43:52  ┆   ┆           ┆           ┆           ┆          │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:43:52  ┆ 17:30:00  ┆ 19:43:52  ┆   ┆           ┆           ┆           ┆          │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:43:52  ┆ 17:37:00  ┆ 19:43:52  ┆   ┆           ┆           ┆           ┆          │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:43:52  ┆ 17:45:00  ┆ 19:43:52  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
df_sepsis_3_v3_all_comb = df_shock_orgrandysfunction_3.join(
    df_shock_orgrandysfunction_3.join(
		df_shock_orgrandysfunction_3.group_by(
			"EncounterEpicCsn"
		).agg(
			pl.col("sepsis_score").max().alias('max_sepsis_score')
		), on="EncounterEpicCsn" , how='inner'
	).filter(
		pl.col('max_sepsis_score') == pl.col('sepsis_score')
	).group_by(
		"EncounterEpicCsn"
	).agg(
		pl.col("sepsis_instance").min(),
		pl.col("max_sepsis_score").first()
	), on=['EncounterEpicCsn', 'sepsis_instance'], how='inner'
)

In [34]:
df_sepsis_3_v3_all_comb.select(
	['EncounterEpicCsn', 'infect_dt', 'Event_DateTime', pl.col('sepsis_instance').alias("sepsis_instant"), 'sepsis_score']
	+
	[c for c in df_shock_orgrandysfunction_3.columns if c.endswith('_flag') or c.endswith('_ratio') or c.endswith('_total')]
).write_csv('./sepsis_3_v3_all_comb.csv')

#### Combining organdysfunc flags with sepsis 2

In [35]:
df_sepsis_2_with_organdysf = df_sepsis_v2.join(
    df_organ_pulmonary_3, on=['EncounterEpicCsn', 'Event_DateTime'], how='left'
).filter(
    pl.col('sepsis_score') == 2
)
df_sepsis_2_with_organdysf

shape: (10_577, 40)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ infect_dt ┆ Event_Dat ┆ sepsis_in ┆ … ┆ vent_doc_ ┆ o2_vent_f ┆ vent_end_ ┆ pulmonar │
│ EpicCsn   ┆ ---       ┆ eTime     ┆ stance    ┆   ┆ flag      ┆ lag       ┆ flag      ┆ y_dysfun │
│ ---       ┆ datetime[ ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ction_fl │
│ i64       ┆ μs]       ┆ datetime[ ┆ datetime[ ┆   ┆ i32       ┆ i32       ┆ i32       ┆ ag       │
│           ┆           ┆ μs]       ┆ μs]       ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆ 4         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 17:52:00  ┆ 17:52:00  ┆   ┆           ┆           ┆           ┆          │
│ 660956097 ┆ 2022-06-2 ┆ 2022-06-2 ┆ 2022-06-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 8         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 06:10:00  ┆ 01:09:00  ┆ 01:09:00  ┆   ┆           ┆           ┆           ┆          │
│ 661424247 ┆ 2022-08-2 ┆ 2022-08-2 ┆ 2022-08-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 8         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 05:30:00  ┆ 02:18:00  ┆ 02:18:00  ┆   ┆           ┆           ┆           ┆          │
│ 661471289 ┆ 2022-06-0 ┆ 2022-06-0 ┆ 2022-06-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 7         ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:47:00  ┆ 12:07:00  ┆ 12:07:00  ┆   ┆           ┆           ┆           ┆          │
│ 662152913 ┆ 2022-08-1 ┆ 2022-08-1 ┆ 2022-08-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆ 5         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 16:45:00  ┆ 17:00:00  ┆ 16:45:00  ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 753545238 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 3         ┆ 3         ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 16:06:00  ┆ 11:51:00  ┆ 11:51:00  ┆   ┆           ┆           ┆           ┆          │
│ 753546980 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 3         ┆ 3         ┆ 3         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 14:11:00  ┆ 15:32:00  ┆ 14:11:00  ┆   ┆           ┆           ┆           ┆          │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆ 4         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 18:39:00  ┆ 18:54:00  ┆ 18:39:00  ┆   ┆           ┆           ┆           ┆          │
│ 753563196 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆ 5         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 04:49:00  ┆ 05:24:00  ┆ 04:49:00  ┆   ┆           ┆           ┆           ┆          │
│ 753579730 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆ 6         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 23:23:00  ┆ 00:00:00  ┆ 23:23:00  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [46]:
df_o2vent_3.drop_nulls(subset=[
    'pf_ratio', 'vent_onoff_flag', 'vent_doc_flag',	'o2_vent_flag',	'vent_end_flag', 'pulmonary_dysfunction_flag'
])

shape: (0, 59)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ EncounterE ┆ Event_Date ┆ Type ┆ Event_Grou ┆ … ┆ vent_doc_f ┆ o2_vent_f ┆ vent_end_ ┆ pulmonary │
│ picCsn     ┆ Time       ┆ ---  ┆ per        ┆   ┆ lag        ┆ lag       ┆ flag      ┆ _dysfunct │
│ ---        ┆ ---        ┆ str  ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ion_flag  │
│ i64        ┆ datetime[μ ┆      ┆ str        ┆   ┆ i32        ┆ i32       ┆ i32       ┆ ---       │
│            ┆ s]         ┆      ┆            ┆   ┆            ┆           ┆           ┆ i32       │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [47]:
df_o2vent_3.select(
    ['EncounterEpicCsn', 'Event_DateTime']+[c for c in df_o2vent_3.columns if c.endswith('_flag') or c.startswith('last_') or c.endswith('_score') or c.endswith('_ratio')]
)

shape: (17_673_744, 8)
┌────────────┬────────────┬──────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ EncounterE ┆ Event_Date ┆ pf_ratio ┆ vent_onoff ┆ vent_doc_f ┆ o2_vent_f ┆ vent_end_ ┆ pulmonary │
│ picCsn     ┆ Time       ┆ ---      ┆ _flag      ┆ lag        ┆ lag       ┆ flag      ┆ _dysfunct │
│ ---        ┆ ---        ┆ f64      ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ion_flag  │
│ i64        ┆ datetime[μ ┆          ┆ i32        ┆ i32        ┆ i32       ┆ i32       ┆ ---       │
│            ┆ s]         ┆          ┆            ┆            ┆           ┆           ┆ i32       │
╞════════════╪════════════╪══════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ 670101787  ┆ 2022-10-13 ┆ null     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      │
│            ┆ 22:10:00   ┆          ┆            ┆            ┆           ┆           ┆           │
│ 692424715  ┆ 2023-11-13 ┆ null     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      │
│            ┆ 10:45:00   ┆          ┆            ┆            ┆           ┆           ┆           │
│ 686550527  ┆ 2023-08-08 ┆ null     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      │
│            ┆ 03:52:00   ┆          ┆            ┆            ┆           ┆           ┆           │
│ 674101030  ┆ 2023-01-08 ┆ null     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      │
│            ┆ 20:45:00   ┆          ┆            ┆            ┆           ┆           ┆           │
│ 690415709  ┆ 2023-10-06 ┆ null     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      │
│            ┆ 19:53:00   ┆          ┆            ┆            ┆           ┆           ┆           │
│ …          ┆ …          ┆ …        ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         │
│ 718191846  ┆ 2024-12-22 ┆ null     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      │
│            ┆ 07:52:00   ┆          ┆            ┆            ┆           ┆           ┆           │
│ 695767263  ┆ 2024-02-04 ┆ null     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      │
│            ┆ 04:00:00   ┆          ┆            ┆            ┆           ┆           ┆           │
│ 746782688  ┆ 2026-04-01 ┆ null     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      │
│            ┆ 13:50:00   ┆          ┆            ┆            ┆           ┆           ┆           │
│ 732022688  ┆ 2025-07-25 ┆ null     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      │
│            ┆ 20:01:00   ┆          ┆            ┆            ┆           ┆           ┆           │
│ 674431120  ┆ 2022-12-26 ┆ null     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      │
│            ┆ 07:00:00   ┆          ┆            ┆            ┆           ┆           ┆           │
└────────────┴────────────┴──────────┴────────────┴────────────┴───────────┴───────────┴───────────┘

In [48]:
df_organdysf_3.select(
    ['EncounterEpicCsn', 'Event_DateTime']+[c for c in df_organdysf_3.columns if c.endswith('_flag') or c.startswith('last_') or c.endswith('_score') or c.endswith('_ratio')]
)

shape: (8_030_274, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ last_temp ┆ last_puls ┆ … ┆ platelets ┆ renal_fai ┆ hepatic_f ┆ neurolog │
│ EpicCsn   ┆ eTime     ┆ _8h       ┆ e_8h      ┆   ┆ 100_crite ┆ lure_flag ┆ ailure_fl ┆ ical_fai │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ria_flag  ┆ ---       ┆ ag        ┆ lure_fla │
│ i64       ┆ datetime[ ┆ f64       ┆ f64       ┆   ┆ ---       ┆ i32       ┆ ---       ┆ g        │
│           ┆ μs]       ┆           ┆           ┆   ┆ i32       ┆           ┆ i32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 659308243 ┆ 2022-06-1 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10:50:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:22:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:23:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ 98.2      ┆ 76.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:52:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ 98.2      ┆ 76.0      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 13:21:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 753774459 ┆ 2026-05-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 15:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 753774459 ┆ 2026-05-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:27:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 753774459 ┆ 2026-05-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:28:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 753774459 ┆ 2026-05-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 07:53:23  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 753774459 ┆ 2026-05-2 ┆ null      ┆ null      ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│           ┆ 9         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 11:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [49]:
df_o2vent_3

shape: (17_673_744, 59)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ vent_doc_ ┆ o2_vent_f ┆ vent_end_ ┆ pulmonar │
│ EpicCsn   ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ flag      ┆ lag       ┆ flag      ┆ y_dysfun │
│ ---       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ction_fl │
│ i64       ┆ datetime[ ┆           ┆ str       ┆   ┆ i32       ┆ i32       ┆ i32       ┆ ag       │
│           ┆ μs]       ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 670101787 ┆ 2022-10-1 ┆ Flowsheet ┆ Pulse     ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 692424715 ┆ 2023-11-1 ┆ Flowsheet ┆ Arterial  ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 3         ┆           ┆ Blood     ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10:45:00  ┆           ┆ Pressure  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Mean      ┆   ┆           ┆           ┆           ┆          │
│ 686550527 ┆ 2023-08-0 ┆ Flowsheet ┆ Weight    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 03:52:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 674101030 ┆ 2023-01-0 ┆ Flowsheet ┆ Pulse     ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:45:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 690415709 ┆ 2023-10-0 ┆ Flowsheet ┆ Respirati ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 6         ┆           ┆ ons       ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:53:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 718191846 ┆ 2024-12-2 ┆ Flowsheet ┆ Blood     ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 2         ┆           ┆ Pressure  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 07:52:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 695767263 ┆ 2024-02-0 ┆ Flowsheet ┆ Arterial  ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 4         ┆           ┆ Blood     ┆   ┆           ┆           ┆           ┆          │
│           ┆ 04:00:00  ┆           ┆ Pressure  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Mean      ┆   ┆           ┆           ┆           ┆          │
│ 746782688 ┆ 2026-04-0 ┆ Flowsheet ┆ Respirati ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 1         ┆           ┆ ons       ┆   ┆           ┆           ┆           ┆          │
│           ┆ 13:50:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 732022688 ┆ 2025-07-2 ┆ Flowsheet ┆ Braden    ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆           ┆ Scale     ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:01:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 674431120 ┆ 2022-12-2 ┆ Flowsheet ┆ Temperatu ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 6         ┆           ┆ re        ┆   ┆           ┆           ┆           ┆          │
│           ┆ 07:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [59]:
df_sepsis_3_with_shock = df_sepsis_3_with_shock.unique()

In [63]:
df_sepsis_3_with_shock.unique(subset=['EncounterEpicCsn', 'sepsis_instance'])

shape: (151_357, 56)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ infect_dt ┆ Event_Dat ┆ sepsis_in ┆ … ┆ vent_doc_ ┆ o2_vent_f ┆ vent_end_ ┆ pulmonar │
│ EpicCsn   ┆ ---       ┆ eTime     ┆ stance    ┆   ┆ flag      ┆ lag       ┆ flag      ┆ y_dysfun │
│ ---       ┆ datetime[ ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ction_fl │
│ i64       ┆ μs]       ┆ datetime[ ┆ datetime[ ┆   ┆ i32       ┆ i32       ┆ i32       ┆ ag       │
│           ┆           ┆ μs]       ┆ μs]       ┆   ┆           ┆           ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 715402795 ┆ 2024-11-0 ┆ 2024-11-0 ┆ 2024-11-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 7         ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 17:21:00  ┆ 07:14:21  ┆ 07:14:21  ┆   ┆           ┆           ┆           ┆          │
│ 696583672 ┆ 2024-01-2 ┆ 2024-01-2 ┆ 2024-01-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 9         ┆ 9         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:14:47  ┆ 00:35:00  ┆ 00:35:00  ┆   ┆           ┆           ┆           ┆          │
│ 676469327 ┆ 2023-02-0 ┆ 2023-02-0 ┆ 2023-02-0 ┆ … ┆ null      ┆ 1         ┆ null      ┆ 1        │
│           ┆ 7         ┆ 6         ┆ 6         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 10:27:50  ┆ 07:36:00  ┆ 07:36:00  ┆   ┆           ┆           ┆           ┆          │
│ 707544369 ┆ 2024-07-1 ┆ 2024-07-1 ┆ 2024-07-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 8         ┆ 7 03:19:4 ┆ 7 03:19:4 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 02:32:00  ┆ 9.503     ┆ 9.503     ┆   ┆           ┆           ┆           ┆          │
│ 686173502 ┆ 2023-08-2 ┆ 2023-08-1 ┆ 2023-08-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 0         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 09:49:00  ┆ 10:45:00  ┆ 10:45:00  ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 671194516 ┆ 2022-10-2 ┆ 2022-10-2 ┆ 2022-10-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆ 5         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 12:23:00  ┆ 08:15:00  ┆ 08:15:00  ┆   ┆           ┆           ┆           ┆          │
│ 688651091 ┆ 2024-01-1 ┆ 2024-01-1 ┆ 2024-01-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 9         ┆ 9         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 16:39:00  ┆ 16:29:00  ┆ 16:29:00  ┆   ┆           ┆           ┆           ┆          │
│ 665597637 ┆ 2022-07-2 ┆ 2022-07-2 ┆ 2022-07-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 7         ┆ 5         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 04:36:42  ┆ 19:15:00  ┆ 19:15:00  ┆   ┆           ┆           ┆           ┆          │
│ 722918442 ┆ 2025-03-1 ┆ 2025-03-1 ┆ 2025-03-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 1        │
│           ┆ 9         ┆ 9         ┆ 9         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 01:29:33  ┆ 00:30:00  ┆ 00:30:00  ┆   ┆           ┆           ┆           ┆          │
│ 668478350 ┆ 2022-09-1 ┆ 2022-09-1 ┆ 2022-09-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 5         ┆ 5         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 02:11:00  ┆ 00:12:00  ┆ 00:12:00  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
df_sepsis_3_with_shock.sort(by=['EncounterEpicCsn', 'sepsis_instance']).select(
    ['EncounterEpicCsn', 'infect_dt', 'Event_DateTime', pl.col("sepsis_instance").alias("sepsis_instant"), 'criterion', 'suspicion_infection_type']
    +
    [c for c in df_sepsis_3_with_shock.columns if c.startswith('last_') or c.endswith('_flag') or c.endswith('_score')]
).join

shape: (960_152, 40)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Encounter ┆ infect_dt ┆ Event_Dat ┆ sepsis_in ┆ … ┆ map65_fla ┆ lactate4_ ┆ vasopress ┆ septic_s │
│ EpicCsn   ┆ ---       ┆ eTime     ┆ stant     ┆   ┆ g         ┆ flag      ┆ or_flag   ┆ hock_fla │
│ ---       ┆ datetime[ ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ g        │
│ i64       ┆ μs]       ┆ datetime[ ┆ datetime[ ┆   ┆ i64       ┆ i64       ┆ i64       ┆ ---      │
│           ┆           ┆ μs]       ┆ μs]       ┆   ┆           ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 4         ┆ 6         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 11:15:00  ┆ 22:10:00  ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ 1         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 4         ┆ 6         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 09:45:00  ┆ 22:10:00  ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 4         ┆ 6         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 15:30:00  ┆ 22:10:00  ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 4         ┆ 6         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 13:30:00  ┆ 22:10:00  ┆   ┆           ┆           ┆           ┆          │
│ 659308243 ┆ 2022-06-1 ┆ 2022-06-1 ┆ 2022-06-1 ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 4         ┆ 5         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 22:10:00  ┆ 22:30:00  ┆ 22:10:00  ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 5         ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:43:52  ┆ 15:00:00  ┆ 19:43:52  ┆   ┆           ┆           ┆           ┆          │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ 1         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 5         ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:43:52  ┆ 13:15:00  ┆ 19:43:52  ┆   ┆           ┆           ┆           ┆          │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 5         ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:43:52  ┆ 12:24:00  ┆ 19:43:52  ┆   ┆           ┆           ┆           ┆          │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 5         ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:43:52  ┆ 12:45:00  ┆ 19:43:52  ┆   ┆           ┆           ┆           ┆          │
│ 753558469 ┆ 2026-05-2 ┆ 2026-05-2 ┆ 2026-05-2 ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1        │
│           ┆ 5         ┆ 7         ┆ 5         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:43:52  ┆ 17:00:00  ┆ 19:43:52  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘