In [49]:
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import os
from pathlib import Path
import datetime as dt

CWD = Path(os.getcwd())
if 'notebooks' in str(CWD):
	sys.path.append(str(CWD.parent))
else:
	sys.path.append(str(CWD))

In [2]:
from src_strategy.utils.utils import load_df
from src_strategy.configs.pulmonarydysfunction import PulmonaryDysfunctionConfig
from src_strategy.configs.dataconfig import input_output_config_3_1

In [3]:
df_all = load_df(input_output_config_3_1.output_path, 'df_all.parquet')

In [4]:
config = PulmonaryDysfunctionConfig()

In [5]:
config.__dict__

{'encounter_col': 'EncounterEpicCsn',
 'event_dt_col': 'Event_DateTime',
 'event_name_col': 'Event_Name',
 'grouper_col': 'Event_Grouper',
 'type_col': 'Type',
 'val_col': 'NumericValue',
 'raw_val_col': 'Value',
 'BASELINE_CREATININE': 'Baseline_Creatinine',
 'BASELINE_SBP': 'Baseline_SBP',
 'BASELINE_RESP_RATE': 'Baseline_RespiratoryRate',
 'BASELINE_PULSE_RATE': 'Baseline_PulseRate',
 'BASELINE_PLATELETS': 'Baseline_Platelets',
 'BASELINE_BILIRUBIN': 'Baseline_Bilirubin',
 'BASELINE_eGFR': 'Baseline_eGFR',
 'BASELINE_WBC': 'Baseline_WBC',
 'vent_onoff': VentOnOffConfig(grouper='Vent On/Off', start_values=['On Going Hospital Vent', 'Initial', '$ On Going Hospital Vent'], termination_values=['Standby', '$ Extubation'], null_value_terminates=True, start_flag_col='vent_onoff_start_flag', termination_flag_col='vent_onoff_termination_flag'),
 'vent_documentation': VentDocumentationConfig(start_grouper='Vent on Documentation', termination_grouper='Vent off Documentation', start_flag_col='vent_documentation_start_flag', termination_flag_col='vent_documentation_termination_flag'),
 'pf': PFConfig(encounter_col='EncounterEpicCsn', event_dt_col='Event_DateTime', event_name_col='Event_Name', grouper_col='Event_Grouper', type_col='Type', val_col='NumericValue', raw_val_col='Value', BASELINE_CREATININE='Baseline_Creatinine', BASELINE_SBP='Baseline_SBP', BASELINE_RESP_RATE='Baseline_RespiratoryRate', BASELINE_PULSE_RATE='Baseline_PulseRate', BASELINE_PLATELETS='Baseline_Platelets', BASELINE_BILIRUBIN='Baseline_Bilirubin', BASELINE_eGFR='Baseline_eGFR', BASELINE_WBC='Baseline_WBC', pao2_grouper_val='PAO2', fio2_grouper_val='FIO2', threshold=200.0, time_window_between_pao2_fio2_hrs=2.0, pf_ratio_col='pf_ratio', pao2_value_col='pf_pao2_value', pao2_time_col='pf_pao2_time', fio2_value_col='pf_fio2_value', fio2_fraction_col='pf_fio2_fraction', fio2_time_col='pf_fio2_time', pf_ratio_time_col='pf_ratio_time', pair_status_col='pf_pair_status', paired_status='paired', invalid_pao2_status='invalid_pao2', no_valid_fio2_status='no_valid_fio2_within_window', start_flag_col='pf_ratio_start_flag', termination_flag_col='pf_ratio_termination_flag', unique_subset_with_grouper=['EncounterEpicCsn', 'Event_DateTime', 'Event_Grouper', 'Value'], unique_subset_with_type=['EncounterEpicCsn', 'Event_DateTime', 'Type', 'Value'], unique_subset_with_eventname=['EncounterEpicCsn', 'Event_DateTime', 'Event_Name', 'Value'], unique_subset_with_all=['EncounterEpicCsn', 'Event_DateTime', 'Type', 'Event_Grouper', 'Event_Name', 'Value'], base_cols=['EncounterEpicCsn', 'Event_DateTime', 'Type', 'Event_Grouper', 'Event_Name', 'NumericValue', 'Value']),
 'o2_delivery': O2DeliveryConfig(mechanical_grouper='O2 Delivery Mechanical Ventilation', mechanical_start_values=['mechanical ventilator', 'ventilator', 'BiPAP', 'CPAP', 'NPPV/NIV'], termination_groupers=['O2 Delivery Nasal Cannula', 'O2 Delivery Simple Face Mask', 'O2 Delivery Room Air'], high_flow_termination_grouper='O2 Delivery High-Flow', high_flow_termination_values=['high-flow nasal cannula', 'high-flow nasal cannula;heated', 'high-flow nasal cannula;humidified', 'humidified;high-flow nasal cannula', 'high-flow mask'], non_rebreather_termination_grouper='O2 Delivery Non-Rebreather Mask', non_rebreather_termination_values=['nonrebreather mask', 'partial rebreather mask', 'blender system'], start_flag_col='mechanical_o2_start_flag', termination_flag_col='o2_delivery_termination_flag'),
 'exclusions': ExcludedEncounterConfig(diagnosis_codes=['Z99.11', 'Z93.0'], home_vent_grouper='Vent On/Off', home_vent_value='$ Home Vent Used', flag_col='pulmonary_exclusion_flag', reason_col='pulmonary_exclusion_reason', evidence_time_col='pulmonary_exclusion_time'),
 'selected_start': [<PulmonaryStartCriterionName.VENT_DOCUMENTATION: 'vent_documentation'>,
  <PulmonaryStartCriterionName.VENT_ON_OFF: 'vent_on_off'>,
  <PulmonaryStartCriterionName.MECHANICAL_O2: 'mechanical_o2'>,
  <PulmonaryStartCriterionName.PF_RATIO: 'pf_ratio'>],
 'selected_termination': [<PulmonaryTerminationCriterionName.VENT_DOCUMENTATION: 'vent_documentation'>,
  <PulmonaryTerminationCriterionName.VENT_ON_OFF: 'vent_on_off'>,
  <PulmonaryTerminationCriterionName.O2_DELIVERY: 'o2_delivery'>,
  <PulmonaryTerminationCriterionName.PF_RATIO: 'pf_ratio'>],
 'start_flag_col': 'pulmonary_start_flag',
 'termination_flag_col': 'pulmonary_termination_flag',
 'transition_state_col': 'pulmonary_transition_state',
 'transition_type_col': 'pulmonary_transition_type',
 'transition_time_col': 'pulmonary_transition_time',
 'state_time_col': 'pulmonary_state_time',
 'segment_start_col': 'segment_start',
 'segment_end_col': 'segment_end',
 'pulmonary_dysfunction_flag': 'pulmonary_dysfunction_flag'}

In [6]:
ventonoff_config = config.vent_onoff
ventdoc_config = config.vent_documentation
vento2_config = config.o2_delivery
exclusion_config = config.exclusions

In [7]:
df_all = df_all.sort([config.encounter_col, config.event_dt_col])

In [8]:
vento2_config

O2DeliveryConfig(mechanical_grouper='O2 Delivery Mechanical Ventilation', mechanical_start_values=['mechanical ventilator', 'ventilator', 'BiPAP', 'CPAP', 'NPPV/NIV'], termination_groupers=['O2 Delivery Nasal Cannula', 'O2 Delivery Simple Face Mask', 'O2 Delivery Room Air'], high_flow_termination_grouper='O2 Delivery High-Flow', high_flow_termination_values=['high-flow nasal cannula', 'high-flow nasal cannula;heated', 'high-flow nasal cannula;humidified', 'humidified;high-flow nasal cannula', 'high-flow mask'], non_rebreather_termination_grouper='O2 Delivery Non-Rebreather Mask', non_rebreather_termination_values=['nonrebreather mask', 'partial rebreather mask', 'blender system'], start_flag_col='mechanical_o2_start_flag', termination_flag_col='o2_delivery_termination_flag')

In [9]:
vent_start_expr = (
	(
		(pl.col(config.grouper_col) == ventonoff_config.grouper)
		&(pl.col(config.raw_val_col).is_in(ventonoff_config.start_values))
	)
	|(
		(pl.col(config.grouper_col) == ventdoc_config.start_grouper)
	)
	|(
		(pl.col(config.grouper_col) == vento2_config.mechanical_grouper)
		&(pl.col(config.raw_val_col).is_in(vento2_config.mechanical_start_values))
	)
)

In [10]:
vento2_config

O2DeliveryConfig(mechanical_grouper='O2 Delivery Mechanical Ventilation', mechanical_start_values=['mechanical ventilator', 'ventilator', 'BiPAP', 'CPAP', 'NPPV/NIV'], termination_groupers=['O2 Delivery Nasal Cannula', 'O2 Delivery Simple Face Mask', 'O2 Delivery Room Air'], high_flow_termination_grouper='O2 Delivery High-Flow', high_flow_termination_values=['high-flow nasal cannula', 'high-flow nasal cannula;heated', 'high-flow nasal cannula;humidified', 'humidified;high-flow nasal cannula', 'high-flow mask'], non_rebreather_termination_grouper='O2 Delivery Non-Rebreather Mask', non_rebreather_termination_values=['nonrebreather mask', 'partial rebreather mask', 'blender system'], start_flag_col='mechanical_o2_start_flag', termination_flag_col='o2_delivery_termination_flag')

In [33]:
ventonoff_config

VentOnOffConfig(grouper='Vent On/Off', start_values=['On Going Hospital Vent', 'Initial', '$ On Going Hospital Vent'], termination_values=['Standby', '$ Extubation'], null_value_terminates=True, start_flag_col='vent_onoff_start_flag', termination_flag_col='vent_onoff_termination_flag')

In [34]:
vent_on_off_termination_values = [
    v for v in ventonoff_config.termination_values if v!='Standby'
]
vent_on_off_termination_values_expr = pl.col(config.raw_val_col).is_in(vent_on_off_termination_values)

if ventonoff_config.null_value_terminates:
    vent_on_off_termination_values_expr = (
		vent_on_off_termination_values_expr | pl.col(config.raw_val_col).is_null()
	)


vent_end_expr = (
	(
		# (pl.col(config.grouper_col) == ventonoff_config.grouper)
		# & ( (pl.col(config.raw_val_col)=='$ Extubation') | pl.col(config.raw_val_col).is_null() )
		(pl.col(config.grouper_col) == ventonoff_config.grouper)
        &vent_on_off_termination_values_expr
	)
	|(
		(pl.col(config.grouper_col) == ventdoc_config.termination_grouper)
	)
	|(
		(pl.col(config.grouper_col) == vento2_config.mechanical_grouper)
		&(pl.col(config.raw_val_col).is_in(vento2_config.termination_groupers))
	)
	|(
		(pl.col(config.grouper_col) == vento2_config.high_flow_termination_grouper)
		&(pl.col(config.raw_val_col).is_in(vento2_config.high_flow_termination_values))
	)
	|(
		(pl.col(config.grouper_col) == vento2_config.non_rebreather_termination_grouper)
		&(pl.col(config.raw_val_col).is_in(vento2_config.non_rebreather_termination_values))
	)
)

In [35]:
df_vent_start_end = df_all.with_columns(
	pl.when(vent_start_expr).then(pl.lit(1)).otherwise(pl.lit(0)).alias("vent_start"),
	pl.when(vent_end_expr).then(pl.lit(1)).otherwise(pl.lit(0)).alias("vent_end"),
).filter( (pl.col("vent_start")>0) | (pl.col("vent_end")>0))

In [36]:
df_vent_start_end.filter(
	((pl.col("vent_start").shift(1).over("EncounterEpicCsn") == 1)&(pl.col("vent_start")==0)& (pl.col("vent_end")==1) )
)

shape: (6_443, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ EncounterE ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ pf_ratio ┆ PF_Ratio_ ┆ vent_star ┆ vent_end │
│ picCsn     ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ ---      ┆ Flag      ┆ t         ┆ ---      │
│ ---        ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ i32      │
│ i64        ┆ datetime[ ┆           ┆ str       ┆   ┆          ┆ i32       ┆ i32       ┆          │
│            ┆ μs]       ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 659308243  ┆ 2022-06-1 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 7         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 13:47:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 659308243  ┆ 2022-06-2 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 5         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 13:00:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 659308243  ┆ 2022-06-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 8         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 11:07:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 659308243  ┆ 2022-06-3 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 0         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 11:17:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 659308243  ┆ 2022-07-0 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 2         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 08:32:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …        │
│ 753113388  ┆ 2026-05-2 ┆ Flowsheet ┆ Vent off  ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 5         ┆           ┆ Documenta ┆   ┆          ┆           ┆           ┆          │
│            ┆ 17:45:00  ┆           ┆ tion      ┆   ┆          ┆           ┆           ┆          │
│ 753347320  ┆ 2026-05-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 0         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 19:30:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 753347320  ┆ 2026-05-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 1         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 10:35:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 753347320  ┆ 2026-05-2 ┆ Flowsheet ┆ Vent off  ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 5         ┆           ┆ Documenta ┆   ┆          ┆           ┆           ┆          │
│            ┆ 10:03:00  ┆           ┆ tion      ┆   ┆          ┆           ┆           ┆          │
│ 753371568  ┆ 2026-05-2 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 6         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 11:00:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

In [37]:
df_vent_start_end.group_by(
	"EncounterEpicCsn"
).agg(pl.col("vent_start").first(), pl.col("vent_end").first()).filter(
	(pl.col("vent_end")==1)&
	(pl.col("vent_start")==0)
)

shape: (2_741, 3)
┌──────────────────┬────────────┬──────────┐
│ EncounterEpicCsn ┆ vent_start ┆ vent_end │
│ ---              ┆ ---        ┆ ---      │
│ i64              ┆ i32        ┆ i32      │
╞══════════════════╪════════════╪══════════╡
│ 661424247        ┆ 0          ┆ 1        │
│ 662851033        ┆ 0          ┆ 1        │
│ 662905347        ┆ 0          ┆ 1        │
│ 663090810        ┆ 0          ┆ 1        │
│ 663374031        ┆ 0          ┆ 1        │
│ …                ┆ …          ┆ …        │
│ 753170359        ┆ 0          ┆ 1        │
│ 753347320        ┆ 0          ┆ 1        │
│ 753425965        ┆ 0          ┆ 1        │
│ 753498904        ┆ 0          ┆ 1        │
│ 753558469        ┆ 0          ┆ 1        │
└──────────────────┴────────────┴──────────┘

In [31]:
df_vent_start_end.filter(pl.col("EncounterEpicCsn")==663374031)

shape: (161, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ EncounterE ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ pf_ratio ┆ PF_Ratio_ ┆ vent_star ┆ vent_end │
│ picCsn     ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ ---      ┆ Flag      ┆ t         ┆ ---      │
│ ---        ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ i32      │
│ i64        ┆ datetime[ ┆           ┆ str       ┆   ┆          ┆ i32       ┆ i32       ┆          │
│            ┆ μs]       ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 663374031  ┆ 2022-06-3 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 0         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 05:50:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 663374031  ┆ 2022-06-3 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 0         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 10:09:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 663374031  ┆ 2022-06-3 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 0         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 10:15:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 663374031  ┆ 2022-06-3 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 0         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 12:45:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 663374031  ┆ 2022-06-3 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 0         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 17:15:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …        │
│ 663374031  ┆ 2022-09-2 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 4         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 03:05:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 663374031  ┆ 2022-09-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 4         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 03:34:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ 663374031  ┆ 2022-09-2 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 4         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 07:15:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 663374031  ┆ 2022-09-2 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 4         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 11:04:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 663374031  ┆ 2022-09-2 ┆ Flowsheet ┆ Vent off  ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 4         ┆           ┆ Documenta ┆   ┆          ┆           ┆           ┆          │
│            ┆ 12:44:00  ┆           ┆ tion      ┆   ┆          ┆           ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

In [28]:
df_vent_start_end.filter(pl.col("EncounterEpicCsn")==661424247)

shape: (116, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ EncounterE ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ pf_ratio ┆ PF_Ratio_ ┆ vent_star ┆ vent_end │
│ picCsn     ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ ---      ┆ Flag      ┆ t         ┆ ---      │
│ ---        ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ i32      │
│ i64        ┆ datetime[ ┆           ┆ str       ┆   ┆          ┆ i32       ┆ i32       ┆          │
│            ┆ μs]       ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 661424247  ┆ 2022-08-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 8         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 02:18:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 661424247  ┆ 2022-08-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 8         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 04:41:00  ┆           ┆ Non-Rebre ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ ather     ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Mas…      ┆   ┆          ┆           ┆           ┆          │
│ 661424247  ┆ 2022-08-2 ┆ Flowsheet ┆ Vent on   ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 8         ┆           ┆ Documenta ┆   ┆          ┆           ┆           ┆          │
│            ┆ 05:15:00  ┆           ┆ tion      ┆   ┆          ┆           ┆           ┆          │
│ 661424247  ┆ 2022-08-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 8         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 05:55:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ 661424247  ┆ 2022-08-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 8         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 07:00:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …        │
│ 661424247  ┆ 2022-09-0 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 9         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 10:22:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ 661424247  ┆ 2022-09-0 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 9         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 20:17:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 661424247  ┆ 2022-09-0 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 9         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 23:06:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 661424247  ┆ 2022-09-1 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 0         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 02:55:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 661424247  ┆ 2022-09-1 ┆ Flowsheet ┆ Vent off  ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 1         ┆           ┆ Documenta ┆   ┆          ┆           ┆           ┆          │
│            ┆ 07:00:00  ┆           ┆ tion      ┆   ┆          ┆           ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

In [43]:
df_vent_start_end.with_columns(
	(pl.col("vent_start").shift(1).over("EncounterEpicCsn") != pl.col("vent_start")).alias("vent_shift")
).with_columns(pl.col("vent_shift").fill_null(False)).with_columns(
	pl.col("vent_shift").cum_sum().over("EncounterEpicCsn").alias("episodes")
).group_by("EncounterEpicCsn", "episodes").agg(pl.col("Event_DateTime").min().alias("begin_dt"), pl.col("Event_DateTime").max().alias("end_dt"), pl.col("Value"), pl.col("vent_start").first().alias('Vent_on'), pl.col("vent_start").len().alias('n_rows')).sort(by=['EncounterEpicCsn', 'episodes'])

shape: (16_985, 7)
┌─────────────────┬──────────┬────────────────┬────────────────┬────────────────┬─────────┬────────┐
│ EncounterEpicCs ┆ episodes ┆ begin_dt       ┆ end_dt         ┆ Value          ┆ Vent_on ┆ n_rows │
│ n               ┆ ---      ┆ ---            ┆ ---            ┆ ---            ┆ ---     ┆ ---    │
│ ---             ┆ u32      ┆ datetime[μs]   ┆ datetime[μs]   ┆ list[str]      ┆ i32     ┆ u64    │
│ i64             ┆          ┆                ┆                ┆                ┆         ┆        │
╞═════════════════╪══════════╪════════════════╪════════════════╪════════════════╪═════════╪════════╡
│ 659308243       ┆ 0        ┆ 2022-06-14     ┆ 2022-06-17     ┆ ["$ Initial",  ┆ 1       ┆ 22     │
│                 ┆          ┆ 21:51:00       ┆ 12:40:00       ┆ "$ On Going    ┆         ┆        │
│                 ┆          ┆                ┆                ┆ Hosp…          ┆         ┆        │
│ 659308243       ┆ 1        ┆ 2022-06-17     ┆ 2022-06-17     ┆ ["$            ┆ 0       ┆ 1      │
│                 ┆          ┆ 13:47:00       ┆ 13:47:00       ┆ Extubation"]   ┆         ┆        │
│ 659308243       ┆ 2        ┆ 2022-06-17     ┆ 2022-06-25     ┆ ["$ Initial",  ┆ 1       ┆ 53     │
│                 ┆          ┆ 19:54:00       ┆ 11:00:00       ┆ "$ On Going    ┆         ┆        │
│                 ┆          ┆                ┆                ┆ Hosp…          ┆         ┆        │
│ 659308243       ┆ 3        ┆ 2022-06-25     ┆ 2022-06-25     ┆ ["$            ┆ 0       ┆ 1      │
│                 ┆          ┆ 13:00:00       ┆ 13:00:00       ┆ Extubation"]   ┆         ┆        │
│ 659308243       ┆ 4        ┆ 2022-06-28     ┆ 2022-06-28     ┆ ["BiPAP"]      ┆ 1       ┆ 1      │
│                 ┆          ┆ 07:08:00       ┆ 07:08:00       ┆                ┆         ┆        │
│ …               ┆ …        ┆ …              ┆ …              ┆ …              ┆ …       ┆ …      │
│ 753371568       ┆ 1        ┆ 2026-05-26     ┆ 2026-05-26     ┆ [null, null,   ┆ 0       ┆ 3      │
│                 ┆          ┆ 11:00:00       ┆ 18:05:00       ┆ "Discontinued" ┆         ┆        │
│                 ┆          ┆                ┆                ┆ ]              ┆         ┆        │
│ 753425965       ┆ 0        ┆ 2026-05-24     ┆ 2026-05-28     ┆ ["nonrebreathe ┆ 0       ┆ 18     │
│                 ┆          ┆ 17:08:00       ┆ 03:00:00       ┆ r mask",       ┆         ┆        │
│                 ┆          ┆                ┆                ┆ "high-f…       ┆         ┆        │
│ 753498904       ┆ 0        ┆ 2026-05-22     ┆ 2026-05-22     ┆ ["nonrebreathe ┆ 0       ┆ 2      │
│                 ┆          ┆ 12:46:00       ┆ 12:50:00       ┆ r mask",       ┆         ┆        │
│                 ┆          ┆                ┆                ┆ "nonreb…       ┆         ┆        │
│ 753558469       ┆ 0        ┆ 2026-05-24     ┆ 2026-05-24     ┆ ["nonrebreathe ┆ 0       ┆ 1      │
│                 ┆          ┆ 18:39:00       ┆ 18:39:00       ┆ r mask"]       ┆         ┆        │
│ 753558469       ┆ 1        ┆ 2026-05-24     ┆ 2026-05-28     ┆ ["BiPAP",      ┆ 1       ┆ 5      │
│                 ┆          ┆ 19:21:00       ┆ 02:16:00       ┆ "BiPAP", …     ┆         ┆        │
│                 ┆          ┆                ┆                ┆ "BiPAP"]       ┆         ┆        │
└─────────────────┴──────────┴────────────────┴────────────────┴────────────────┴─────────┴────────┘

In [18]:
df_vent_null_ventonoff = df_vent_start_end.filter(
	(pl.col("Event_Grouper") == "Vent On/Off")&
	pl.col("Value").is_null()
)

In [24]:
df_vent_null_preceeded_by_vent = df_vent_null_ventonoff.select("EncounterEpicCsn", "Event_DateTime", "Event_Grouper", "Value").join_asof(
    df_vent_start_end.filter(
        	~((pl.col("Event_Grouper") == "Vent On/Off")&
			pl.col("Value").is_null())
	).select("EncounterEpicCsn", pl.col("Event_DateTime").alias('Event_DateTime_all'), "Event_Grouper", "Value"), 
	left_on = "Event_DateTime",
	right_on = "Event_DateTime_all",
	by="EncounterEpicCsn",
    strategy="backward",
    suffix='all'
)

/tmp/ipykernel_2819740/1576885736.py:1: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  df_vent_null_preceeded_by_vent = df_vent_null_ventonoff.select("EncounterEpicCsn", "Event_DateTime", "Event_Grouper", "Value").join_asof(

In [61]:
df_vent_null_preceeded_by_vent.with_columns(
    (pl.col("Event_DateTime")-pl.col("Event_DateTime_all")).dt.total_hours(fractional=True).alias("hours_from_vent_to_null")
).filter(
    pl.col("hours_from_vent_to_null") == 0
)

shape: (52, 8)
┌────────────┬────────────┬────────────┬───────┬────────────┬────────────┬────────────┬────────────┐
│ EncounterE ┆ Event_Date ┆ Event_Grou ┆ Value ┆ Event_Date ┆ Event_Grou ┆ Valueall   ┆ hours_from │
│ picCsn     ┆ Time       ┆ per        ┆ ---   ┆ Time_all   ┆ perall     ┆ ---        ┆ _vent_to_n │
│ ---        ┆ ---        ┆ ---        ┆ str   ┆ ---        ┆ ---        ┆ str        ┆ ull        │
│ i64        ┆ datetime[μ ┆ str        ┆       ┆ datetime[μ ┆ str        ┆            ┆ ---        │
│            ┆ s]         ┆            ┆       ┆ s]         ┆            ┆            ┆ f64        │
╞════════════╪════════════╪════════════╪═══════╪════════════╪════════════╪════════════╪════════════╡
│ 664211059  ┆ 2022-09-19 ┆ Vent       ┆ null  ┆ 2022-09-19 ┆ O2         ┆ ventilator ┆ 0.0        │
│            ┆ 00:55:00   ┆ On/Off     ┆       ┆ 00:55:00   ┆ Delivery   ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Mechanical ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Ventila…   ┆            ┆            │
│ 667146450  ┆ 2022-08-25 ┆ Vent       ┆ null  ┆ 2022-08-25 ┆ O2         ┆ ventilator ┆ 0.0        │
│            ┆ 07:00:00   ┆ On/Off     ┆       ┆ 07:00:00   ┆ Delivery   ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Mechanical ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Ventila…   ┆            ┆            │
│ 669821634  ┆ 2022-10-21 ┆ Vent       ┆ null  ┆ 2022-10-21 ┆ O2         ┆ ventilator ┆ 0.0        │
│            ┆ 00:21:00   ┆ On/Off     ┆       ┆ 00:21:00   ┆ Delivery   ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Mechanical ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Ventila…   ┆            ┆            │
│ 673279459  ┆ 2022-12-04 ┆ Vent       ┆ null  ┆ 2022-12-04 ┆ O2         ┆ ventilator ┆ 0.0        │
│            ┆ 13:55:00   ┆ On/Off     ┆       ┆ 13:55:00   ┆ Delivery   ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Mechanical ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Ventila…   ┆            ┆            │
│ 673348701  ┆ 2022-12-15 ┆ Vent       ┆ null  ┆ 2022-12-15 ┆ O2         ┆ ventilator ┆ 0.0        │
│            ┆ 15:30:00   ┆ On/Off     ┆       ┆ 15:30:00   ┆ Delivery   ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Mechanical ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Ventila…   ┆            ┆            │
│ …          ┆ …          ┆ …          ┆ …     ┆ …          ┆ …          ┆ …          ┆ …          │
│ 739776319  ┆ 2025-11-10 ┆ Vent       ┆ null  ┆ 2025-11-10 ┆ O2         ┆ ventilator ┆ 0.0        │
│            ┆ 07:40:00   ┆ On/Off     ┆       ┆ 07:40:00   ┆ Delivery   ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Mechanical ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Ventila…   ┆            ┆            │
│ 744908255  ┆ 2026-03-20 ┆ Vent       ┆ null  ┆ 2026-03-20 ┆ O2         ┆ ventilator ┆ 0.0        │
│            ┆ 19:00:00   ┆ On/Off     ┆       ┆ 19:00:00   ┆ Delivery   ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Mechanical ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Ventila…   ┆            ┆            │
│ 746128968  ┆ 2026-02-26 ┆ Vent       ┆ null  ┆ 2026-02-26 ┆ O2         ┆ ventilator ┆ 0.0        │
│            ┆ 12:40:00   ┆ On/Off     ┆       ┆ 12:40:00   ┆ Delivery   ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Mechanical ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Ventila…   ┆            ┆            │
│ 748937463  ┆ 2026-04-02 ┆ Vent       ┆ null  ┆ 2026-04-02 ┆ O2         ┆ ventilator ┆ 0.0        │
│            ┆ 07:00:00   ┆ On/Off     ┆       ┆ 07:00:00   ┆ Delivery   ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Mechanical ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Ventila…   ┆            ┆            │
│ 750522065  ┆ 2026-04-18 ┆ Vent       ┆ null  ┆ 2026-04-18 ┆ O2         ┆ ventilator ┆ 0.0        │
│            ┆ 07:00:00   ┆ On/Off     ┆       ┆ 07:00:00   ┆ Delivery   ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Mechanical ┆            ┆            │
│            ┆            ┆            ┆       ┆            ┆ Ventila…   ┆            ┆            │
└────────────┴────────────┴────────────┴───────┴────────────┴────────────┴────────────┴────────────┘

In [ ]:
d = {}
for rows in df_vent_null_preceeded_by_vent.iter_rows(named=True):
    d[(rows['Event_Grouperall'], rows['Valueall'])] = d.get((rows['Event_Grouperall'], rows['Valueall']), 0)+1

In [32]:
sorted(d.items(), key=lambda kv: -kv[1])

[(('Vent On/Off', '$ On Going Hospital Vent'), 497),
 (('O2 Delivery Mechanical Ventilation', 'ventilator'), 294),
 (('Vent On/Off', 'On Going Hospital Vent'), 130),
 (('Vent off Documentation', 'Discontinued'), 31),
 ((None, None), 23),
 (('Vent on Documentation', '$ Initial'), 15),
 (('O2 Delivery Mechanical Ventilation', 'BiPAP'), 14),
 (('O2 Delivery High-Flow', 'humidified;high-flow nasal cannula'), 9),
 (('O2 Delivery High-Flow', 'high-flow nasal cannula'), 7),
 (('O2 Delivery Non-Rebreather Mask', 'nonrebreather mask'), 6),
 (('O2 Delivery High-Flow', 'high-flow nasal cannula;humidified'), 4),
 (('Vent On/Off', '$ Extubation'), 3),
 (('O2 Delivery High-Flow', 'high-flow nasal cannula;heated'), 3),
 (('Vent On/Off', 'Initial'), 3),
 (('O2 Delivery Mechanical Ventilation', 'NPPV/NIV'), 2)]

### Continue with the AI analysis

In [40]:
df_vent_start = (
    df_vent_start_end.filter(
		pl.col("vent_start") == 1
	).select(
        config.encounter_col,
        pl.col("Event_DateTime").alias("vent_start_dt"),
        pl.col("Event_Grouper").alias("vent_start_grouper"),
        pl.col("Value").alias("vent_start_value"),
	)
    .sort(by=[config.encounter_col, 'vent_start_dt'])
	.with_row_index("vent_start_evidence_id", offset=1)
)
df_vent_start

shape: (268_594, 5)
┌─────────────────────┬──────────────────┬───────────────┬────────────────────┬────────────────────┐
│ vent_start_evidence ┆ EncounterEpicCsn ┆ vent_start_dt ┆ vent_start_grouper ┆ vent_start_value   │
│ _id                 ┆ ---              ┆ ---           ┆ ---                ┆ ---                │
│ ---                 ┆ i64              ┆ datetime[μs]  ┆ str                ┆ str                │
│ u64                 ┆                  ┆               ┆                    ┆                    │
╞═════════════════════╪══════════════════╪═══════════════╪════════════════════╪════════════════════╡
│ 1                   ┆ 659308243        ┆ 2022-06-14    ┆ Vent on            ┆ $ Initial          │
│                     ┆                  ┆ 21:51:00      ┆ Documentation      ┆                    │
│ 2                   ┆ 659308243        ┆ 2022-06-14    ┆ Vent On/Off        ┆ $ On Going         │
│                     ┆                  ┆ 22:36:00      ┆                    ┆ Hospital Vent      │
│ 3                   ┆ 659308243        ┆ 2022-06-15    ┆ Vent On/Off        ┆ $ On Going         │
│                     ┆                  ┆ 00:12:00      ┆                    ┆ Hospital Vent      │
│ 4                   ┆ 659308243        ┆ 2022-06-15    ┆ Vent On/Off        ┆ $ On Going         │
│                     ┆                  ┆ 02:55:00      ┆                    ┆ Hospital Vent      │
│ 5                   ┆ 659308243        ┆ 2022-06-15    ┆ Vent On/Off        ┆ $ On Going         │
│                     ┆                  ┆ 04:54:00      ┆                    ┆ Hospital Vent      │
│ …                   ┆ …                ┆ …             ┆ …                  ┆ …                  │
│ 268590              ┆ 753558469        ┆ 2026-05-24    ┆ O2 Delivery        ┆ BiPAP              │
│                     ┆                  ┆ 19:21:00      ┆ Mechanical         ┆                    │
│                     ┆                  ┆               ┆ Ventila…           ┆                    │
│ 268591              ┆ 753558469        ┆ 2026-05-24    ┆ O2 Delivery        ┆ BiPAP              │
│                     ┆                  ┆ 21:15:00      ┆ Mechanical         ┆                    │
│                     ┆                  ┆               ┆ Ventila…           ┆                    │
│ 268592              ┆ 753558469        ┆ 2026-05-27    ┆ O2 Delivery        ┆ BiPAP              │
│                     ┆                  ┆ 19:18:00      ┆ Mechanical         ┆                    │
│                     ┆                  ┆               ┆ Ventila…           ┆                    │
│ 268593              ┆ 753558469        ┆ 2026-05-27    ┆ O2 Delivery        ┆ BiPAP              │
│                     ┆                  ┆ 23:42:00      ┆ Mechanical         ┆                    │
│                     ┆                  ┆               ┆ Ventila…           ┆                    │
│ 268594              ┆ 753558469        ┆ 2026-05-28    ┆ O2 Delivery        ┆ BiPAP              │
│                     ┆                  ┆ 02:16:00      ┆ Mechanical         ┆                    │
│                     ┆                  ┆               ┆ Ventila…           ┆                    │
└─────────────────────┴──────────────────┴───────────────┴────────────────────┴────────────────────┘

In [ ]:
df_vent_end = (
    df_vent_start_end
    .filter(pl.col("vent_end") == 1)
	 .group_by(config.encounter_col, config.event_dt_col)
    .agg(
        pl.col(config.grouper_col)
        .unique()
        .sort()
        .alias("vent_termination_groupers"),

        pl.col(config.raw_val_col)
        .drop_nulls()
        .unique()
        .sort()
        .alias("vent_termination_values"),
    )
    .rename({config.event_dt_col: "vent_termination_dt"})
    .sort(config.encounter_col, "vent_termination_dt")
)
df_vent_end.select(
	pl.col('vent_termination_groupers').list.len()
)['vent_termination_groupers'].max()

2

In [48]:
df_vent_end.filter(
	pl.col('vent_termination_groupers').list.len() == 2
)

shape: (84, 4)
┌──────────────────┬─────────────────────┬───────────────────────────┬─────────────────────────┐
│ EncounterEpicCsn ┆ vent_termination_dt ┆ vent_termination_groupers ┆ vent_termination_values │
│ ---              ┆ ---                 ┆ ---                       ┆ ---                     │
│ i64              ┆ datetime[μs]        ┆ list[str]                 ┆ list[str]               │
╞══════════════════╪═════════════════════╪═══════════════════════════╪═════════════════════════╡
│ 663374031        ┆ 2022-07-25 10:39:00 ┆ ["O2 Delivery High-Flow", ┆ ["$ Extubation",        │
│                  ┆                     ┆ "Ven…                     ┆ "high-flow na…          │
│ 663879519        ┆ 2022-07-03 11:00:00 ┆ ["O2 Delivery High-Flow", ┆ ["Discontinued",        │
│                  ┆                     ┆ "Ven…                     ┆ "high-flow na…          │
│ 664010526        ┆ 2022-07-03 15:50:00 ┆ ["O2 Delivery High-Flow", ┆ ["Discontinued",        │
│                  ┆                     ┆ "Ven…                     ┆ "high-flow na…          │
│ 664754198        ┆ 2022-07-22 12:30:00 ┆ ["O2 Delivery High-Flow", ┆ ["Discontinued",        │
│                  ┆                     ┆ "Ven…                     ┆ "high-flow na…          │
│ 667686916        ┆ 2022-09-06 09:45:00 ┆ ["O2 Delivery High-Flow", ┆ ["Discontinued",        │
│                  ┆                     ┆ "Ven…                     ┆ "high-flow na…          │
│ …                ┆ …                   ┆ …                         ┆ …                       │
│ 747154189        ┆ 2026-02-25 07:45:00 ┆ ["O2 Delivery High-Flow", ┆ ["Discontinued",        │
│                  ┆                     ┆ "Ven…                     ┆ "high-flow na…          │
│ 747410809        ┆ 2026-03-14 17:23:00 ┆ ["O2 Delivery High-Flow", ┆ ["Discontinued",        │
│                  ┆                     ┆ "Ven…                     ┆ "high-flow na…          │
│ 748831725        ┆ 2026-03-24 12:55:00 ┆ ["O2 Delivery High-Flow", ┆ ["Discontinued",        │
│                  ┆                     ┆ "Ven…                     ┆ "high-flow na…          │
│ 750299750        ┆ 2026-04-13 08:45:00 ┆ ["O2 Delivery High-Flow", ┆ ["Discontinued",        │
│                  ┆                     ┆ "Ven…                     ┆ "high-flow na…          │
│ 751626084        ┆ 2026-05-07 09:20:00 ┆ ["O2 Delivery High-Flow", ┆ ["Discontinued",        │
│                  ┆                     ┆ "Ven…                     ┆ "high-flow na…          │
└──────────────────┴─────────────────────┴───────────────────────────┴─────────────────────────┘

In [50]:
df_vent_start_end.filter(
    (pl.col("EncounterEpicCsn") == 748831725)&
    (pl.col("Event_DateTime") == dt.datetime(2026, 3, 24, 12, 55))
)

shape: (2, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ EncounterE ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ pf_ratio ┆ PF_Ratio_ ┆ vent_star ┆ vent_end │
│ picCsn     ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ ---      ┆ Flag      ┆ t         ┆ ---      │
│ ---        ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ i32      │
│ i64        ┆ datetime[ ┆           ┆ str       ┆   ┆          ┆ i32       ┆ i32       ┆          │
│            ┆ μs]       ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 748831725  ┆ 2026-03-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 4         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 12:55:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 748831725  ┆ 2026-03-2 ┆ Flowsheet ┆ Vent off  ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 4         ┆           ┆ Documenta ┆   ┆          ┆           ┆           ┆          │
│            ┆ 12:55:00  ┆           ┆ tion      ┆   ┆          ┆           ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

In [92]:
df_vent_start_end.group_by(
    "EncounterEpicCsn", "Event_DateTime"
).agg(
	pl.col("vent_start").unique().sort(),
	pl.col("vent_end").unique().sort(),
).filter(
    (pl.col("vent_start").list.len()>1)
    |
    (pl.col("vent_end").list.len()>1)
).filter(
    pl.col("EncounterEpicCsn") == 663374031
)

shape: (0, 4)
┌──────────────────┬────────────────┬────────────┬───────────┐
│ EncounterEpicCsn ┆ Event_DateTime ┆ vent_start ┆ vent_end  │
│ ---              ┆ ---            ┆ ---        ┆ ---       │
│ i64              ┆ datetime[μs]   ┆ list[i32]  ┆ list[i32] │
╞══════════════════╪════════════════╪════════════╪═══════════╡
└──────────────────┴────────────────┴────────────┴───────────┘

In [56]:
df_vent_start_end.filter(
    (pl.col("EncounterEpicCsn") == 736836690)
    &(pl.col("Event_DateTime") == dt.datetime(2025, 10, 31, 21))
)

shape: (2, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ EncounterE ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ pf_ratio ┆ PF_Ratio_ ┆ vent_star ┆ vent_end │
│ picCsn     ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ ---      ┆ Flag      ┆ t         ┆ ---      │
│ ---        ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ i32      │
│ i64        ┆ datetime[ ┆           ┆ str       ┆   ┆          ┆ i32       ┆ i32       ┆          │
│            ┆ μs]       ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 736836690  ┆ 2025-10-3 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 1         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 21:00:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ 736836690  ┆ 2025-10-3 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 1         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 21:00:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

In [78]:
df_vent_start_end.group_by(
    "EncounterEpicCsn", "Event_DateTime"
).agg(
	pl.col("vent_start").unique().sort(),
	pl.col("vent_end").unique().sort(),
).filter(
    (pl.col("vent_start").list.len()>1)
    |
    (pl.col("vent_end").list.len()>1)
).select(
    pl.col("vent_start").list.len().max().alias('max_vent_start_len'),
    pl.col("vent_end").list.len().max().alias('max_vent_end_len')
)

shape: (1, 2)
┌────────────────────┬──────────────────┐
│ max_vent_start_len ┆ max_vent_end_len │
│ ---                ┆ ---              │
│ u64                ┆ u64              │
╞════════════════════╪══════════════════╡
│ 2                  ┆ 2                │
└────────────────────┴──────────────────┘

In [79]:
df_on_off_vent_0 = df_vent_start_end.group_by(
    "EncounterEpicCsn", "Event_DateTime"
).agg(
	pl.col("vent_start").unique().sort(),
	pl.col("vent_end").unique().sort(),
).filter(
    (pl.col("vent_start").list.len()>1)
    |
    (pl.col("vent_end").list.len()>1)
)

df_0_vent2null = df_vent_null_preceeded_by_vent.with_columns(
    (pl.col("Event_DateTime")-pl.col("Event_DateTime_all")).dt.total_hours(fractional=True).alias("hours_from_vent_to_null")
).filter(
    pl.col("hours_from_vent_to_null") == 0
).select("EncounterEpicCsn", "Event_DateTime")

In [80]:
df_on_off_vent_0_not_null = df_on_off_vent_0.join(df_0_vent2null, how='anti', on=['EncounterEpicCsn', 'Event_DateTime'])

In [88]:
d_grouper = {}
for row in df_on_off_vent_0_not_null.iter_rows(named=True):
	df_sub = (df_vent_start_end.filter(
		(pl.col("EncounterEpicCsn") == row[config.encounter_col])
		&(pl.col("Event_DateTime") == row[config.event_dt_col])
	))
	key1 = (df_sub[0]['Event_Grouper'].item(), df_sub[0]['Value'].item(),
		df_sub[1]['Event_Grouper'].item(), df_sub[1]['Value'].item() )
	key2 = (df_sub[1]['Event_Grouper'].item(), df_sub[1]['Value'].item(),
		df_sub[0]['Event_Grouper'].item(), df_sub[0]['Value'].item() )
	d_grouper[key1] = d_grouper.get(key1, 0) + 1
	d_grouper[key2] = d_grouper.get(key2, 0) + 1

In [93]:
df_on_off_vent_0_not_null

shape: (47, 4)
┌──────────────────┬─────────────────────┬────────────┬───────────┐
│ EncounterEpicCsn ┆ Event_DateTime      ┆ vent_start ┆ vent_end  │
│ ---              ┆ ---                 ┆ ---        ┆ ---       │
│ i64              ┆ datetime[μs]        ┆ list[i32]  ┆ list[i32] │
╞══════════════════╪═════════════════════╪════════════╪═══════════╡
│ 711743163        ┆ 2024-10-28 13:00:00 ┆ [0, 1]     ┆ [0, 1]    │
│ 744112293        ┆ 2026-02-16 13:00:00 ┆ [0, 1]     ┆ [0, 1]    │
│ 698435519        ┆ 2024-02-21 10:33:00 ┆ [0, 1]     ┆ [0, 1]    │
│ 699388833        ┆ 2024-03-08 09:48:00 ┆ [0, 1]     ┆ [0, 1]    │
│ 734482652        ┆ 2025-09-01 17:50:00 ┆ [0, 1]     ┆ [0, 1]    │
│ …                ┆ …                   ┆ …          ┆ …         │
│ 747431997        ┆ 2026-03-04 14:05:00 ┆ [0, 1]     ┆ [0, 1]    │
│ 705075651        ┆ 2024-06-09 09:35:00 ┆ [0, 1]     ┆ [0, 1]    │
│ 721527751        ┆ 2025-03-12 11:50:00 ┆ [0, 1]     ┆ [0, 1]    │
│ 672969271        ┆ 2022-12-01 11:15:00 ┆ [0, 1]     ┆ [0, 1]    │
│ 717006646        ┆ 2025-03-09 23:15:00 ┆ [0, 1]     ┆ [0, 1]    │
└──────────────────┴─────────────────────┴────────────┴───────────┘

In [91]:
sorted(d_grouper.items(), key=lambda kv: -kv[1])

[(('Vent off Documentation',
   'Discontinued',
   'O2 Delivery Mechanical Ventilation',
   'BiPAP'),
  28),
 (('O2 Delivery Mechanical Ventilation',
   'BiPAP',
   'Vent off Documentation',
   'Discontinued'),
  28),
 (('Vent off Documentation',
   'Discontinued',
   'O2 Delivery Mechanical Ventilation',
   'ventilator'),
  7),
 (('O2 Delivery Mechanical Ventilation',
   'ventilator',
   'Vent off Documentation',
   'Discontinued'),
  7),
 (('O2 Delivery High-Flow',
   'high-flow nasal cannula',
   'Vent On/Off',
   '$ On Going Hospital Vent'),
  5),
 (('Vent On/Off',
   '$ On Going Hospital Vent',
   'O2 Delivery High-Flow',
   'high-flow nasal cannula'),
  5),
 (('O2 Delivery Mechanical Ventilation',
   'NPPV/NIV',
   'Vent off Documentation',
   'Discontinued'),
  4),
 (('Vent off Documentation',
   'Discontinued',
   'O2 Delivery Mechanical Ventilation',
   'NPPV/NIV'),
  4),
 (('Vent on Documentation',
   '$ Initial',
   'O2 Delivery Non-Rebreather Mask',
   'nonrebreather mask'),
  2),
 (('O2 Delivery Non-Rebreather Mask',
   'nonrebreather mask',
   'Vent on Documentation',
   '$ Initial'),
  2),
 (('O2 Delivery High-Flow',
   'humidified;high-flow nasal cannula',
   'Vent on Documentation',
   '$ Initial'),
  1),
 (('Vent on Documentation',
   '$ Initial',
   'O2 Delivery High-Flow',
   'humidified;high-flow nasal cannula'),
  1)]

In [86]:
df_sub

shape: (2, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ EncounterE ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ pf_ratio ┆ PF_Ratio_ ┆ vent_star ┆ vent_end │
│ picCsn     ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ ---      ┆ Flag      ┆ t         ┆ ---      │
│ ---        ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ i32      │
│ i64        ┆ datetime[ ┆           ┆ str       ┆   ┆          ┆ i32       ┆ i32       ┆          │
│            ┆ μs]       ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 711743163  ┆ 2024-10-2 ┆ Flowsheet ┆ Vent off  ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 8         ┆           ┆ Documenta ┆   ┆          ┆           ┆           ┆          │
│            ┆ 13:00:00  ┆           ┆ tion      ┆   ┆          ┆           ┆           ┆          │
│ 711743163  ┆ 2024-10-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 8         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 13:00:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

In [ ]:
df_anti_vent_start_end = df_vent_start_end.join(
    df_on_off_vent_0.select("EncounterEpicCsn", "Event_DateTime"),
	on=['EncounterEpicCsn', 'Event_DateTime'],
    how='anti'
)

shape: (334_829, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ EncounterE ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ pf_ratio ┆ PF_Ratio_ ┆ vent_star ┆ vent_end │
│ picCsn     ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ ---      ┆ Flag      ┆ t         ┆ ---      │
│ ---        ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ i32      │
│ i64        ┆ datetime[ ┆           ┆ str       ┆   ┆          ┆ i32       ┆ i32       ┆          │
│            ┆ μs]       ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 659308243  ┆ 2022-06-1 ┆ Flowsheet ┆ Vent on   ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 4         ┆           ┆ Documenta ┆   ┆          ┆           ┆           ┆          │
│            ┆ 21:51:00  ┆           ┆ tion      ┆   ┆          ┆           ┆           ┆          │
│ 659308243  ┆ 2022-06-1 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 4         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 22:36:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 659308243  ┆ 2022-06-1 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 5         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 00:12:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 659308243  ┆ 2022-06-1 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 5         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 02:55:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 659308243  ┆ 2022-06-1 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 5         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 04:54:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …        │
│ 753558469  ┆ 2026-05-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 4         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 19:21:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ 753558469  ┆ 2026-05-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 4         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 21:15:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ 753558469  ┆ 2026-05-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 7         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 19:18:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ 753558469  ┆ 2026-05-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 7         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 23:42:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ 753558469  ┆ 2026-05-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 8         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 02:16:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

In [103]:
df_on_off_vent_0_not_null.join_asof(
    df_anti_vent_start_end.select(
        config.encounter_col,
        pl.col(config.event_dt_col).alias('start_or_end_dt'),
        config.grouper_col,
        config.raw_val_col
	),
    left_on="Event_DateTime",
	right_on="start_or_end_dt",
	by='EncounterEpicCsn',
    strategy='forward'
).filter(
    pl.col("Event_Grouper").is_not_null()
)

/tmp/ipykernel_2819740/1045624455.py:1: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  df_on_off_vent_0_not_null.join_asof(

shape: (41, 7)
┌──────────────┬──────────────┬────────────┬───────────┬──────────────┬──────────────┬─────────────┐
│ EncounterEpi ┆ Event_DateTi ┆ vent_start ┆ vent_end  ┆ start_or_end ┆ Event_Groupe ┆ Value       │
│ cCsn         ┆ me           ┆ ---        ┆ ---       ┆ _dt          ┆ r            ┆ ---         │
│ ---          ┆ ---          ┆ list[i32]  ┆ list[i32] ┆ ---          ┆ ---          ┆ str         │
│ i64          ┆ datetime[μs] ┆            ┆           ┆ datetime[μs] ┆ str          ┆             │
╞══════════════╪══════════════╪════════════╪═══════════╪══════════════╪══════════════╪═════════════╡
│ 711743163    ┆ 2024-10-28   ┆ [0, 1]     ┆ [0, 1]    ┆ 2024-10-31   ┆ O2 Delivery  ┆ high-flow   │
│              ┆ 13:00:00     ┆            ┆           ┆ 08:47:00     ┆ High-Flow    ┆ nasal       │
│              ┆              ┆            ┆           ┆              ┆              ┆ cannula     │
│ 744112293    ┆ 2026-02-16   ┆ [0, 1]     ┆ [0, 1]    ┆ 2026-02-16   ┆ O2 Delivery  ┆ BiPAP       │
│              ┆ 13:00:00     ┆            ┆           ┆ 14:48:00     ┆ Mechanical   ┆             │
│              ┆              ┆            ┆           ┆              ┆ Ventila…     ┆             │
│ 698435519    ┆ 2024-02-21   ┆ [0, 1]     ┆ [0, 1]    ┆ 2024-02-21   ┆ O2 Delivery  ┆ ventilator  │
│              ┆ 10:33:00     ┆            ┆           ┆ 11:10:00     ┆ Mechanical   ┆             │
│              ┆              ┆            ┆           ┆              ┆ Ventila…     ┆             │
│ 699388833    ┆ 2024-03-08   ┆ [0, 1]     ┆ [0, 1]    ┆ 2024-03-08   ┆ O2 Delivery  ┆ BiPAP       │
│              ┆ 09:48:00     ┆            ┆           ┆ 10:56:00     ┆ Mechanical   ┆             │
│              ┆              ┆            ┆           ┆              ┆ Ventila…     ┆             │
│ 693573011    ┆ 2023-11-27   ┆ [0, 1]     ┆ [0, 1]    ┆ 2023-11-27   ┆ O2 Delivery  ┆ BiPAP       │
│              ┆ 07:00:00     ┆            ┆           ┆ 10:15:00     ┆ Mechanical   ┆             │
│              ┆              ┆            ┆           ┆              ┆ Ventila…     ┆             │
│ …            ┆ …            ┆ …          ┆ …         ┆ …            ┆ …            ┆ …           │
│ 674367576    ┆ 2022-12-28   ┆ [0, 1]     ┆ [0, 1]    ┆ 2022-12-29   ┆ O2 Delivery  ┆ BiPAP       │
│              ┆ 13:25:00     ┆            ┆           ┆ 08:06:00     ┆ Mechanical   ┆             │
│              ┆              ┆            ┆           ┆              ┆ Ventila…     ┆             │
│ 747431997    ┆ 2026-03-04   ┆ [0, 1]     ┆ [0, 1]    ┆ 2026-03-04   ┆ O2 Delivery  ┆ BiPAP       │
│              ┆ 14:05:00     ┆            ┆           ┆ 15:06:00     ┆ Mechanical   ┆             │
│              ┆              ┆            ┆           ┆              ┆ Ventila…     ┆             │
│ 705075651    ┆ 2024-06-09   ┆ [0, 1]     ┆ [0, 1]    ┆ 2024-06-09   ┆ O2 Delivery  ┆ ventilator  │
│              ┆ 09:35:00     ┆            ┆           ┆ 13:15:00     ┆ Mechanical   ┆             │
│              ┆              ┆            ┆           ┆              ┆ Ventila…     ┆             │
│ 721527751    ┆ 2025-03-12   ┆ [0, 1]     ┆ [0, 1]    ┆ 2025-03-12   ┆ O2 Delivery  ┆ BiPAP       │
│              ┆ 11:50:00     ┆            ┆           ┆ 15:20:00     ┆ Mechanical   ┆             │
│              ┆              ┆            ┆           ┆              ┆ Ventila…     ┆             │
│ 717006646    ┆ 2025-03-09   ┆ [0, 1]     ┆ [0, 1]    ┆ 2025-03-10   ┆ Vent On/Off  ┆ $ On Going  │
│              ┆ 23:15:00     ┆            ┆           ┆ 01:00:00     ┆              ┆ Hospital    │
│              ┆              ┆            ┆           ┆              ┆              ┆ Vent        │
└──────────────┴──────────────┴────────────┴───────────┴──────────────┴──────────────┴─────────────┘

In [106]:
df_vent_start_end.filter(
    (pl.col("EncounterEpicCsn") == 674367576)
    &(pl.col("Event_DateTime") == dt.datetime(2022, 12, 28, 13, 25))
)

shape: (2, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ EncounterE ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ pf_ratio ┆ PF_Ratio_ ┆ vent_star ┆ vent_end │
│ picCsn     ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ ---      ┆ Flag      ┆ t         ┆ ---      │
│ ---        ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ i32      │
│ i64        ┆ datetime[ ┆           ┆ str       ┆   ┆          ┆ i32       ┆ i32       ┆          │
│            ┆ μs]       ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 674367576  ┆ 2022-12-2 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 8         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 13:25:00  ┆           ┆ Mechanica ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ l         ┆   ┆          ┆           ┆           ┆          │
│            ┆           ┆           ┆ Ventila…  ┆   ┆          ┆           ┆           ┆          │
│ 674367576  ┆ 2022-12-2 ┆ Flowsheet ┆ Vent off  ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 8         ┆           ┆ Documenta ┆   ┆          ┆           ┆           ┆          │
│            ┆ 13:25:00  ┆           ┆ tion      ┆   ┆          ┆           ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘

In [107]:
df_vent_start_end.filter(
    (pl.col("EncounterEpicCsn") == 705075651)
    # &(pl.col("Event_DateTime") == dt.datetime(2024, 12, 28, 13, 25))
)

shape: (64, 14)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬──────────┐
│ EncounterE ┆ Event_Dat ┆ Type      ┆ Event_Gro ┆ … ┆ pf_ratio ┆ PF_Ratio_ ┆ vent_star ┆ vent_end │
│ picCsn     ┆ eTime     ┆ ---       ┆ uper      ┆   ┆ ---      ┆ Flag      ┆ t         ┆ ---      │
│ ---        ┆ ---       ┆ str       ┆ ---       ┆   ┆ f64      ┆ ---       ┆ ---       ┆ i32      │
│ i64        ┆ datetime[ ┆           ┆ str       ┆   ┆          ┆ i32       ┆ i32       ┆          │
│            ┆ μs]       ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪══════════╡
│ 705075651  ┆ 2024-06-0 ┆ Flowsheet ┆ Vent on   ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 6         ┆           ┆ Documenta ┆   ┆          ┆           ┆           ┆          │
│            ┆ 18:20:00  ┆           ┆ tion      ┆   ┆          ┆           ┆           ┆          │
│ 705075651  ┆ 2024-06-0 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 6         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 19:15:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 705075651  ┆ 2024-06-0 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 6         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 23:10:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 705075651  ┆ 2024-06-0 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 7         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 03:15:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ 705075651  ┆ 2024-06-0 ┆ Flowsheet ┆ Vent      ┆ … ┆ null     ┆ null      ┆ 1         ┆ 0        │
│            ┆ 7         ┆           ┆ On/Off    ┆   ┆          ┆           ┆           ┆          │
│            ┆ 08:10:00  ┆           ┆           ┆   ┆          ┆           ┆           ┆          │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …        ┆ …         ┆ …         ┆ …        │
│ 705075651  ┆ 2024-06-1 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 5         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 10:42:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 705075651  ┆ 2024-06-1 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 5         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 14:29:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 705075651  ┆ 2024-06-1 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 5         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 15:59:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 705075651  ┆ 2024-06-1 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 5         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 19:00:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
│ 705075651  ┆ 2024-06-1 ┆ Flowsheet ┆ O2        ┆ … ┆ null     ┆ null      ┆ 0         ┆ 1        │
│            ┆ 6         ┆           ┆ Delivery  ┆   ┆          ┆           ┆           ┆          │
│            ┆ 22:57:00  ┆           ┆ High-Flow ┆   ┆          ┆           ┆           ┆          │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴──────────┘